package defpackage;

import com.vk.push.core.base.AidlException;
import org.apache.http.HttpStatus;

/* JADX INFO: loaded from: classes3.dex */
public enum f4b implements lrc {
    EMPTY_CHAT(100),
    INVALID_EMPTY_MESSAGE(101),
    INVALID_SEND_EMPTY_MESSAGE(102),
    EMPTY_FORWARDS(AidlException.HOST_IS_NOT_MASTER),
    EMPTY_STICKER_ID(AidlException.SDK_IS_NOT_INITIALIZED),
    EMPTY_DIALOG_CONTACT(AidlException.TRANSFERRED_IPC_DATA_EXCEPTION),
    FAIL_TO_PREPARE_MEDIA(106),
    FAIL_TO_PARSE_LOCATION_RESULT(107),
    EMPTY_URI_ON_FILE_ACTIVITY_RESULT(108),
    EMPTY_CONTACT_REQUEST_RESULT(109),
    EMPTY_SHARE_DATA(110),
    NO_LOGGER(111),
    EMPTY_MESSAGE_ID(112),
    EMPTY_MESSAGE(113),
    EMPTY_SHARE_COLLAGE_DATA(114),
    NON_EXISTED_CHAT_IN_SERVICE_TASK(200),
    BUILT_NULL_MESSAGE(201),
    INSERTED_MSG_NULL(202),
    MISSED_SEND_FLOW(203),
    NON_EXISTED_MESSAGE_IN_SERVICE_TASK(204),
    EMPTY_DELAYED_ATTRS(205),
    NON_EXISTED_COMMENTS_CHAT_IN_SERVICE_TASK(206),
    NON_EXISTED_MESSAGE_IN_API_TASK(300),
    EMPTY_OUTGOING_MESSAGE(301),
    EMPTY_MESSAGE_IN_API_TASK(HttpStatus.SC_MOVED_TEMPORARILY),
    MESSAGE_UNEXPECTED_DELETED_STATUS(HttpStatus.SC_SEE_OTHER),
    UNKNOWN_ERROR_GET_OUTGOING(HttpStatus.SC_NOT_MODIFIED),
    UNKNOWN_ERROR_HANDLE_SUCCESS(HttpStatus.SC_USE_PROXY),
    NON_EXISTED_MESSAGE_ON_FAIL(306),
    BAD_REQUEST(HttpStatus.SC_TEMPORARY_REDIRECT),
    UPLOAD_FAILED(308),
    NOTIF_ATTACH_ERROR(309),
    MSG_AUTO_DELETED_EMPTY(313),
    MESSAGE_LIMIT_ERROR(314),
    MESSAGE_PERMISSION_ERROR(315),
    MSG_DELETED_BEFORE_SEND(HttpStatus.SC_BAD_REQUEST),
    MSG_DELETED_DURING_SEND(HttpStatus.SC_UNAUTHORIZED);

    public final int a;

    f4b(int i) {
        this.a = i;
    }

    @Override // defpackage.lrc
    public final int a() {
        return this.a;
    }
}
