package defpackage;

import android.R;

/* JADX INFO: loaded from: classes.dex */
public abstract class k3e {
    public static final int[] a = {R.attr.background, R.attr.touchscreenBlocksFocus, R.attr.keyboardNavigationCluster, ru.oneme.app.R.attr.elevation, ru.oneme.app.R.attr.expanded, ru.oneme.app.R.attr.liftOnScroll, ru.oneme.app.R.attr.liftOnScrollColor, ru.oneme.app.R.attr.liftOnScrollTargetViewId, ru.oneme.app.R.attr.statusBarForeground};
    public static final int[] b = {ru.oneme.app.R.attr.layout_scrollEffect, ru.oneme.app.R.attr.layout_scrollFlags, ru.oneme.app.R.attr.layout_scrollInterpolator};
    public static final int[] c = {ru.oneme.app.R.attr.autoAdjustToWithinGrandparentBounds, ru.oneme.app.R.attr.backgroundColor, ru.oneme.app.R.attr.badgeGravity, ru.oneme.app.R.attr.badgeHeight, ru.oneme.app.R.attr.badgeRadius, ru.oneme.app.R.attr.badgeShapeAppearance, ru.oneme.app.R.attr.badgeShapeAppearanceOverlay, ru.oneme.app.R.attr.badgeText, ru.oneme.app.R.attr.badgeTextAppearance, ru.oneme.app.R.attr.badgeTextColor, ru.oneme.app.R.attr.badgeVerticalPadding, ru.oneme.app.R.attr.badgeWidePadding, ru.oneme.app.R.attr.badgeWidth, ru.oneme.app.R.attr.badgeWithTextHeight, ru.oneme.app.R.attr.badgeWithTextRadius, ru.oneme.app.R.attr.badgeWithTextShapeAppearance, ru.oneme.app.R.attr.badgeWithTextShapeAppearanceOverlay, ru.oneme.app.R.attr.badgeWithTextWidth, ru.oneme.app.R.attr.horizontalOffset, ru.oneme.app.R.attr.horizontalOffsetWithText, ru.oneme.app.R.attr.largeFontVerticalOffsetAdjustment, ru.oneme.app.R.attr.maxCharacterCount, ru.oneme.app.R.attr.maxNumber, ru.oneme.app.R.attr.number, ru.oneme.app.R.attr.offsetAlignmentMode, ru.oneme.app.R.attr.verticalOffset, ru.oneme.app.R.attr.verticalOffsetWithText};
    public static final int[] d = {R.attr.indeterminate, ru.oneme.app.R.attr.hideAnimationBehavior, ru.oneme.app.R.attr.indicatorColor, ru.oneme.app.R.attr.indicatorTrackGapSize, ru.oneme.app.R.attr.minHideDelay, ru.oneme.app.R.attr.showAnimationBehavior, ru.oneme.app.R.attr.showDelay, ru.oneme.app.R.attr.trackColor, ru.oneme.app.R.attr.trackCornerRadius, ru.oneme.app.R.attr.trackThickness};
    public static final int[] e = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, ru.oneme.app.R.attr.backgroundTint, ru.oneme.app.R.attr.behavior_draggable, ru.oneme.app.R.attr.behavior_expandedOffset, ru.oneme.app.R.attr.behavior_fitToContents, ru.oneme.app.R.attr.behavior_halfExpandedRatio, ru.oneme.app.R.attr.behavior_hideable, ru.oneme.app.R.attr.behavior_peekHeight, ru.oneme.app.R.attr.behavior_saveFlags, ru.oneme.app.R.attr.behavior_significantVelocityThreshold, ru.oneme.app.R.attr.behavior_skipCollapsed, ru.oneme.app.R.attr.gestureInsetBottomIgnored, ru.oneme.app.R.attr.marginLeftSystemWindowInsets, ru.oneme.app.R.attr.marginRightSystemWindowInsets, ru.oneme.app.R.attr.marginTopSystemWindowInsets, ru.oneme.app.R.attr.paddingBottomSystemWindowInsets, ru.oneme.app.R.attr.paddingLeftSystemWindowInsets, ru.oneme.app.R.attr.paddingRightSystemWindowInsets, ru.oneme.app.R.attr.paddingTopSystemWindowInsets, ru.oneme.app.R.attr.shapeAppearance, ru.oneme.app.R.attr.shapeAppearanceOverlay, ru.oneme.app.R.attr.shouldRemoveExpandedCorners};
    public static final int[] f = {ru.oneme.app.R.attr.carousel_alignment, ru.oneme.app.R.attr.carousel_backwardTransition, ru.oneme.app.R.attr.carousel_emptyViewsBehavior, ru.oneme.app.R.attr.carousel_firstView, ru.oneme.app.R.attr.carousel_forwardTransition, ru.oneme.app.R.attr.carousel_infinite, ru.oneme.app.R.attr.carousel_nextState, ru.oneme.app.R.attr.carousel_previousState, ru.oneme.app.R.attr.carousel_touchUpMode, ru.oneme.app.R.attr.carousel_touchUp_dampeningFactor, ru.oneme.app.R.attr.carousel_touchUp_velocityThreshold};
    public static final int[] g = {R.attr.textAppearance, R.attr.textSize, R.attr.textColor, R.attr.ellipsize, R.attr.maxWidth, R.attr.text, R.attr.checkable, ru.oneme.app.R.attr.checkedIcon, ru.oneme.app.R.attr.checkedIconEnabled, ru.oneme.app.R.attr.checkedIconTint, ru.oneme.app.R.attr.checkedIconVisible, ru.oneme.app.R.attr.chipBackgroundColor, ru.oneme.app.R.attr.chipCornerRadius, ru.oneme.app.R.attr.chipEndPadding, ru.oneme.app.R.attr.chipIcon, ru.oneme.app.R.attr.chipIconEnabled, ru.oneme.app.R.attr.chipIconSize, ru.oneme.app.R.attr.chipIconTint, ru.oneme.app.R.attr.chipIconVisible, ru.oneme.app.R.attr.chipMinHeight, ru.oneme.app.R.attr.chipMinTouchTargetSize, ru.oneme.app.R.attr.chipStartPadding, ru.oneme.app.R.attr.chipStrokeColor, ru.oneme.app.R.attr.chipStrokeWidth, ru.oneme.app.R.attr.chipSurfaceColor, ru.oneme.app.R.attr.closeIcon, ru.oneme.app.R.attr.closeIconEnabled, ru.oneme.app.R.attr.closeIconEndPadding, ru.oneme.app.R.attr.closeIconSize, ru.oneme.app.R.attr.closeIconStartPadding, ru.oneme.app.R.attr.closeIconTint, ru.oneme.app.R.attr.closeIconVisible, ru.oneme.app.R.attr.ensureMinTouchTargetSize, ru.oneme.app.R.attr.hideMotionSpec, ru.oneme.app.R.attr.iconEndPadding, ru.oneme.app.R.attr.iconStartPadding, ru.oneme.app.R.attr.rippleColor, ru.oneme.app.R.attr.shapeAppearance, ru.oneme.app.R.attr.shapeAppearanceOverlay, ru.oneme.app.R.attr.showMotionSpec, ru.oneme.app.R.attr.textEndPadding, ru.oneme.app.R.attr.textStartPadding};
    public static final int[] h = {ru.oneme.app.R.attr.checkedChip, ru.oneme.app.R.attr.chipSpacing, ru.oneme.app.R.attr.chipSpacingHorizontal, ru.oneme.app.R.attr.chipSpacingVertical, ru.oneme.app.R.attr.selectionRequired, ru.oneme.app.R.attr.singleLine, ru.oneme.app.R.attr.singleSelection};
    public static final int[] i = {ru.oneme.app.R.attr.indicatorDirectionCircular, ru.oneme.app.R.attr.indicatorInset, ru.oneme.app.R.attr.indicatorSize};
    public static final int[] j = {ru.oneme.app.R.attr.collapsedTitleGravity, ru.oneme.app.R.attr.collapsedTitleTextAppearance, ru.oneme.app.R.attr.collapsedTitleTextColor, ru.oneme.app.R.attr.contentScrim, ru.oneme.app.R.attr.expandedTitleGravity, ru.oneme.app.R.attr.expandedTitleMargin, ru.oneme.app.R.attr.expandedTitleMarginBottom, ru.oneme.app.R.attr.expandedTitleMarginEnd, ru.oneme.app.R.attr.expandedTitleMarginStart, ru.oneme.app.R.attr.expandedTitleMarginTop, ru.oneme.app.R.attr.expandedTitleTextAppearance, ru.oneme.app.R.attr.expandedTitleTextColor, ru.oneme.app.R.attr.extraMultilineHeightEnabled, ru.oneme.app.R.attr.forceApplySystemWindowInsetTop, ru.oneme.app.R.attr.maxLines, ru.oneme.app.R.attr.scrimAnimationDuration, ru.oneme.app.R.attr.scrimVisibleHeightTrigger, ru.oneme.app.R.attr.statusBarScrim, ru.oneme.app.R.attr.title, ru.oneme.app.R.attr.titleCollapseMode, ru.oneme.app.R.attr.titleEnabled, ru.oneme.app.R.attr.titlePositionInterpolator, ru.oneme.app.R.attr.titleTextEllipsize, ru.oneme.app.R.attr.toolbarId};
    public static final int[] k = {ru.oneme.app.R.attr.layout_collapseMode, ru.oneme.app.R.attr.layout_collapseParallaxMultiplier};
    public static final int[] l = {ru.oneme.app.R.attr.behavior_autoHide, ru.oneme.app.R.attr.behavior_autoShrink};
    public static final int[] m = {ru.oneme.app.R.attr.behavior_autoHide};
    public static final int[] n = {ru.oneme.app.R.attr.itemSpacing, ru.oneme.app.R.attr.lineSpacing};
    public static final int[] o = {ru.oneme.app.R.attr.indeterminateAnimationType, ru.oneme.app.R.attr.indicatorDirectionLinear, ru.oneme.app.R.attr.trackStopIndicatorSize};
    public static final int[] p = {R.attr.inputType, R.attr.popupElevation, ru.oneme.app.R.attr.dropDownBackgroundTint, ru.oneme.app.R.attr.simpleItemLayout, ru.oneme.app.R.attr.simpleItemSelectedColor, ru.oneme.app.R.attr.simpleItemSelectedRippleColor, ru.oneme.app.R.attr.simpleItems};
    public static final int[] q = {R.attr.background, R.attr.insetLeft, R.attr.insetRight, R.attr.insetTop, R.attr.insetBottom, R.attr.checkable, ru.oneme.app.R.attr.backgroundTint, ru.oneme.app.R.attr.backgroundTintMode, ru.oneme.app.R.attr.cornerRadius, ru.oneme.app.R.attr.elevation, ru.oneme.app.R.attr.icon, ru.oneme.app.R.attr.iconGravity, ru.oneme.app.R.attr.iconPadding, ru.oneme.app.R.attr.iconSize, ru.oneme.app.R.attr.iconTint, ru.oneme.app.R.attr.iconTintMode, ru.oneme.app.R.attr.rippleColor, ru.oneme.app.R.attr.shapeAppearance, ru.oneme.app.R.attr.shapeAppearanceOverlay, ru.oneme.app.R.attr.strokeColor, ru.oneme.app.R.attr.strokeWidth, ru.oneme.app.R.attr.toggleCheckedStateOnClick};
    public static final int[] r = {R.attr.enabled, ru.oneme.app.R.attr.checkedButton, ru.oneme.app.R.attr.selectionRequired, ru.oneme.app.R.attr.singleSelection};
    public static final int[] s = {R.attr.button, ru.oneme.app.R.attr.buttonCompat, ru.oneme.app.R.attr.buttonIcon, ru.oneme.app.R.attr.buttonIconTint, ru.oneme.app.R.attr.buttonIconTintMode, ru.oneme.app.R.attr.buttonTint, ru.oneme.app.R.attr.centerIfNoTextEnabled, ru.oneme.app.R.attr.checkedState, ru.oneme.app.R.attr.errorAccessibilityLabel, ru.oneme.app.R.attr.errorShown, ru.oneme.app.R.attr.useMaterialThemeColors};
    public static final int[] t = {ru.oneme.app.R.attr.buttonTint, ru.oneme.app.R.attr.useMaterialThemeColors};
    public static final int[] u = {ru.oneme.app.R.attr.shapeAppearance, ru.oneme.app.R.attr.shapeAppearanceOverlay};
    public static final int[] v = {R.attr.letterSpacing, R.attr.lineHeight, ru.oneme.app.R.attr.lineHeight};
    public static final int[] w = {R.attr.textAppearance, R.attr.lineHeight, ru.oneme.app.R.attr.lineHeight};
    public static final int[] x = {ru.oneme.app.R.attr.behavior_overlapTop};
    public static final int[] y = {ru.oneme.app.R.attr.cornerFamily, ru.oneme.app.R.attr.cornerFamilyBottomLeft, ru.oneme.app.R.attr.cornerFamilyBottomRight, ru.oneme.app.R.attr.cornerFamilyTopLeft, ru.oneme.app.R.attr.cornerFamilyTopRight, ru.oneme.app.R.attr.cornerSize, ru.oneme.app.R.attr.cornerSizeBottomLeft, ru.oneme.app.R.attr.cornerSizeBottomRight, ru.oneme.app.R.attr.cornerSizeTopLeft, ru.oneme.app.R.attr.cornerSizeTopRight};
    public static final int[] z = {R.attr.maxWidth, R.attr.maxHeight, R.attr.elevation, ru.oneme.app.R.attr.backgroundTint, ru.oneme.app.R.attr.behavior_draggable, ru.oneme.app.R.attr.coplanarSiblingViewId, ru.oneme.app.R.attr.shapeAppearance, ru.oneme.app.R.attr.shapeAppearanceOverlay};
    public static final int[] A = {ru.oneme.app.R.attr.tabBackground, ru.oneme.app.R.attr.tabContentStart, ru.oneme.app.R.attr.tabGravity, ru.oneme.app.R.attr.tabIconTint, ru.oneme.app.R.attr.tabIconTintMode, ru.oneme.app.R.attr.tabIndicator, ru.oneme.app.R.attr.tabIndicatorAnimationDuration, ru.oneme.app.R.attr.tabIndicatorAnimationMode, ru.oneme.app.R.attr.tabIndicatorColor, ru.oneme.app.R.attr.tabIndicatorFullWidth, ru.oneme.app.R.attr.tabIndicatorGravity, ru.oneme.app.R.attr.tabIndicatorHeight, ru.oneme.app.R.attr.tabInlineLabel, ru.oneme.app.R.attr.tabMaxWidth, ru.oneme.app.R.attr.tabMinWidth, ru.oneme.app.R.attr.tabMode, ru.oneme.app.R.attr.tabPadding, ru.oneme.app.R.attr.tabPaddingBottom, ru.oneme.app.R.attr.tabPaddingEnd, ru.oneme.app.R.attr.tabPaddingStart, ru.oneme.app.R.attr.tabPaddingTop, ru.oneme.app.R.attr.tabRippleColor, ru.oneme.app.R.attr.tabSelectedTextAppearance, ru.oneme.app.R.attr.tabSelectedTextColor, ru.oneme.app.R.attr.tabTextAppearance, ru.oneme.app.R.attr.tabTextColor, ru.oneme.app.R.attr.tabUnboundedRipple};
    public static final int[] B = {R.attr.textSize, R.attr.typeface, R.attr.textStyle, R.attr.textColor, R.attr.textColorHint, R.attr.textColorLink, R.attr.shadowColor, R.attr.shadowDx, R.attr.shadowDy, R.attr.shadowRadius, R.attr.fontFamily, R.attr.textFontWeight, ru.oneme.app.R.attr.fontFamily, ru.oneme.app.R.attr.fontVariationSettings, ru.oneme.app.R.attr.textAllCaps, ru.oneme.app.R.attr.textLocale};
    public static final int[] C = {R.attr.textAppearance, ru.oneme.app.R.attr.enforceMaterialTheme, ru.oneme.app.R.attr.enforceTextAppearance};
}
