package defpackage;

import com.vk.push.core.base.AidlException;
import java.util.HashMap;

/* JADX INFO: loaded from: classes.dex */
public final class kfc extends Enum {
    public static final kfc J3;
    public static final kfc K3;
    public static final kfc L3;
    public static final kfc M3;
    public static final kfc N3;
    public static final kfc O3;
    public static final kfc P3;
    public static final kfc Q3;
    public static final kfc R3;
    public static final kfc S3;
    public static final kfc T3;
    public static final kfc U3;
    public static final kfc V3;
    public static final kfc W3;
    public static final kfc X3;
    public static final /* synthetic */ kfc[] Y3;
    public static final /* synthetic */ ma6 Z3;
    public static final lhb c;
    public static final HashMap d;
    public static final HashMap e;
    public final short a;
    public final fu3 b;
    public static final kfc f = new kfc("PING", 0, 1, null);
    public static final kfc g = new kfc("DEBUG", 1, 2, null);
    public static final kfc h = new kfc("RECONNECT", 2, 3, null);
    public static final kfc i = new kfc("LOG", 3, 5, null);
    public static final kfc j = new kfc("SESSION_INIT", 4, 6, null);
    public static final kfc k = new kfc("PROFILE", 5, 16, null);
    public static final kfc l = new kfc("AUTH_REQUEST", 6, 17, null);
    public static final kfc m = new kfc("AUTH", 7, 18, null);
    public static final kfc n = new kfc("LOGIN", 8, 19, a8g.k);
    public static final kfc o = new kfc("LOGIN2", 9, 8, xvc.i);
    public static final kfc p = new kfc("LOGOUT", 10, 20, null);
    public static final kfc q = new kfc("SYNC", 11, 21, null);
    public static final kfc r = new kfc("CONFIG", 12, 22, xvc.f);
    public static final kfc s = new kfc("AUTH_CONFIRM", 13, 23, null);
    public static final kfc t = new kfc("AUTH_CREATE_TRACK", 14, 112, cy5.b);
    public static final kfc u = new kfc("AUTH_CHECK_PASSWORD", 15, 113, j85.c);
    public static final kfc v = new kfc("AUTH_LOGIN_CHECK_PASSWORD", 16, 115, ghb.c);
    public static final kfc w = new kfc("AUTH_LOGIN_PROFILE_DELETE", 17, 116, khb.c);
    public static final kfc x = new kfc("AUTH_LOGIN_RESTORE_PASSWORD", 18, 101, lhb.c);
    public static final kfc y = new kfc("AUTH_VALIDATE_PASSWORD", 19, 107, me0.c);
    public static final kfc z = new kfc("AUTH_VALIDATE_HINT", 20, 108, me0.b);
    public static final kfc A = new kfc("AUTH_VERIFY_EMAIL", 21, 109, nhb.c);
    public static final kfc B = new kfc("AUTH_CHECK_EMAIL", 22, 110, a8g.d);
    public static final kfc C = new kfc("AUTH_SET_2FA", 23, 111, me0.a);
    public static final kfc D = new kfc("AUTH_2FA_DETAILS", 24, 104, xvc.c);
    public static final kfc E = new kfc("ASSETS_GET", 25, 26, null);
    public static final kfc F = new kfc("ASSETS_UPDATE", 26, 27, null);
    public static final kfc G = new kfc("ASSETS_GET_BY_IDS", 27, 28, null);
    public static final kfc H = new kfc("ASSETS_LIST_MODIFY", 28, 261, null);
    public static final kfc I = new kfc("ASSETS_REMOVE", 29, 259, null);
    public static final kfc J = new kfc("ASSETS_MOVE", 30, 260, null);
    public static final kfc K = new kfc("ASSETS_ADD", 31, 29, null);
    public static final kfc X = new kfc("PRESET_AVATARS", 32, 25, xvc.l);
    public static final kfc Y = new kfc("CONTACT_INFO", 33, 32, cy5.d);
    public static final kfc Z = new kfc("CONTACT_INFO_BY_PHONE", 34, 46, j85.f);
    public static final kfc n1 = new kfc("CONTACT_ADD", 35, 33, null);
    public static final kfc o1 = new kfc("CONTACT_UPDATE", 36, 34, null);
    public static final kfc p1 = new kfc("CONTACT_PRESENCE", 37, 35, ghb.f);
    public static final kfc q1 = new kfc("CONTACT_LIST", 38, 36, null);
    public static final kfc r1 = new kfc("CONTACT_SEARCH", 39, 37, null);
    public static final kfc s1 = new kfc("CONTACT_PHOTOS", 40, 39, null);
    public static final kfc t1 = new kfc("CONTACT_SORT", 41, 40, null);
    public static final kfc u1 = new kfc("CONTACT_VERIFY", 42, 42, null);
    public static final kfc v1 = new kfc("REMOVE_CONTACT_PHOTO", 43, 43, null);
    public static final kfc w1 = new kfc("CHAT_INFO", 44, 48, null);
    public static final kfc x1 = new kfc("CHAT_HISTORY", 45, 49, null);
    public static final kfc y1 = new kfc("CHAT_MARK", 46, 50, ku6.e);
    public static final kfc z1 = new kfc("CHAT_MEDIA", 47, 51, null);
    public static final kfc A1 = new kfc("CHAT_DELETE", 48, 52, null);
    public static final kfc B1 = new kfc("CHATS_LIST", 49, 53, null);
    public static final kfc C1 = new kfc("CHAT_CLEAR", 50, 54, null);
    public static final kfc D1 = new kfc("CHAT_UPDATE", 51, 55, null);
    public static final kfc E1 = new kfc("CHAT_CHECK_LINK", 52, 56, null);
    public static final kfc F1 = new kfc("CHAT_JOIN", 53, 57, nhb.d);
    public static final kfc G1 = new kfc("CHAT_LEAVE", 54, 58, null);
    public static final kfc H1 = new kfc("CHAT_MEMBERS", 55, 59, xvc.e);
    public static final kfc I1 = new kfc("PUBLIC_SEARCH", 56, 60, null);
    public static final kfc J1 = new kfc("CHAT_PERSONAL_CONFIG", 57, 61, a8g.f);
    public static final kfc K1 = new kfc("REACTIONS_SETTINGS_GET_BY_CHAT_ID", 58, 258, lhb.d);
    public static final kfc L1 = new kfc("CHAT_REACTIONS_SETTINGS_SET", 59, 257, j85.e);
    public static final kfc M1 = new kfc("CHAT_CHECK_ESIA", 60, 307, me0.d);
    public static final kfc N1 = new kfc("MSG_SEND", 61, 64);
    public static final kfc O1 = new kfc("MSG_TYPING", 62, 65);
    public static final kfc P1 = new kfc("MSG_DELETE", 63, 66);
    public static final kfc Q1 = new kfc("MSG_EDIT", 64, 67);
    public static final kfc R1 = new kfc("GET_COMMENTS_UPDATES", 65, 91, ghb.h);
    public static final kfc S1 = new kfc("MSG_DELETE_RANGE", 66, 92);
    public static final kfc T1 = new kfc("MSG_REACTION", 67, 178, gp0.k);
    public static final kfc U1 = new kfc("MSG_CANCEL_REACTION", 68, 179, cy5.g);
    public static final kfc V1 = new kfc("MSG_GET_REACTIONS", 69, 180, nhb.i);
    public static final kfc W1 = new kfc("MSG_GET_DETAILED_REACTIONS", 70, 181);
    public static final kfc X1 = new kfc("STORIES_LIST", 71, 208, nhb.l);
    public static final kfc Y1 = new kfc("STORIES_LIST_BY_OWNER_ID", 72, 209, lhb.m);
    public static final kfc Z1 = new kfc("STORIES_GET_BY_OWNER_ID", 73, 210, j85.m);
    public static final kfc a2 = new kfc("STORIES_GET_STATS", 74, 211, khb.l);
    public static final kfc b2 = new kfc("STORIES_GET_DETAILED_STATS", 75, 212, ghb.l);
    public static final kfc c2 = new kfc("STORIES_REACT", 76, 213, ku6.o);
    public static final kfc d2 = new kfc("STORIES_MARK", 77, 214, gp0.o);
    public static final kfc e2 = new kfc("STORIES_SEND", 78, 215, xvc.n);
    public static final kfc f2 = new kfc("NOTIF_STORIES_UPDATE", 79, 216, j85.k);
    public static final kfc g2 = new kfc("STORIES_EDIT", 80, 217, a8g.n);
    public static final kfc h2 = new kfc("STORIES_DELETE", 81, 218, xvc.m);
    public static final kfc i2 = new kfc("STORIES_GET_BY_STORY_ID", 82, 220, cy5.k);
    public static final kfc j2 = new kfc("CHAT_SEARCH", 83, 68);
    public static final kfc k2 = new kfc("MSG_SHARE_PREVIEW", 84, 70);
    public static final kfc l2 = new kfc("MSG_GET", 85, 71, khb.h);
    public static final kfc m2 = new kfc("MSG_SEARCH_TOUCH", 86, 72);
    public static final kfc n2 = new kfc("MSG_SEARCH", 87, 73);
    public static final kfc o2 = new kfc("MSG_GET_STAT", 88, 74);
    public static final kfc p2 = new kfc("CHAT_SUBSCRIBE", 89, 75);
    public static final kfc q2 = new kfc("VIDEO_CHAT_START", 90, 76, ghb.d);
    public static final kfc r2 = new kfc("VIDEO_CHAT_START_ACTIVE", 91, 78, cy5.m);
    public static final kfc s2 = new kfc("VIDEO_CHAT_JOIN", 92, 166, j85.o);
    public static final kfc t2 = new kfc("VIDEO_CHAT_HANGUP", 93, 167, a8g.p);
    public static final kfc u2 = new kfc("CHAT_MEMBERS_UPDATE", 94, 77);
    public static final kfc v2 = new kfc("VIDEO_CHAT_HISTORY", 95, 79);
    public static final kfc w2 = new kfc("PHOTO_UPLOAD", 96, 80, xvc.b);
    public static final kfc x2 = new kfc("STICKER_UPLOAD", 97, 81);
    public static final kfc y2 = new kfc("VIDEO_UPLOAD", 98, 82, ghb.n);
    public static final kfc z2 = new kfc("VIDEO_PLAY", 99, 83);
    public static final kfc A2 = new kfc("VIDEO_CHAT_CREATE_JOIN_LINK", 100, 84, xvc.d);
    public static final kfc B2 = new kfc("CHAT_PIN_SET_VISIBILITY", 101, 86);
    public static final kfc C2 = new kfc("FILE_UPLOAD", 102, 87);
    public static final kfc D2 = new kfc("FILE_DOWNLOAD", AidlException.HOST_IS_NOT_MASTER, 88, nhb.g);
    public static final kfc E2 = new kfc("LINK_INFO", AidlException.SDK_IS_NOT_INITIALIZED, 89, gp0.j);
    public static final kfc F2 = new kfc("SESSIONS_INFO", AidlException.TRANSFERRED_IPC_DATA_EXCEPTION, 96);
    public static final kfc G2 = new kfc("SESSIONS_CLOSE", 106, 97);
    public static final kfc H2 = new kfc("PHONE_BIND_REQUEST", 107, 98);
    public static final kfc I2 = new kfc("PHONE_BIND_CONFIRM", 108, 99);
    public static final kfc J2 = new kfc("GET_INBOUND_CALLS", 109, 103);
    public static final kfc K2 = new kfc("EXTERNAL_CALLBACK", 110, 105, lhb.g);
    public static final kfc L2 = new kfc("PHONE_WEBAPP_SHARE", 111, 106, gp0.q);
    public static final kfc M2 = new kfc("OK_TOKEN", 112, 158, cy5.i);
    public static final kfc N2 = new kfc("CHAT_COMPLAIN", 113, 117);
    public static final kfc O2 = new kfc("MSG_SEND_CALLBACK", 114, 118);
    public static final kfc P2 = new kfc("SUSPEND_BOT", 115, 119);
    public static final kfc Q2 = new kfc("LOCATION_STOP", 116, 124);
    public static final kfc R2 = new kfc("LOCATION_SEND", 117, 125);
    public static final kfc S2 = new kfc("LOCATION_REQUEST", 118, 126);
    public static final kfc T2 = new kfc("GET_LAST_MENTIONS", 119, 127);
    public static final kfc U2 = new kfc("STICKER_CREATE", 120, 193);
    public static final kfc V2 = new kfc("STICKER_SUGGEST", 121, 194);
    public static final kfc W2 = new kfc("VIDEO_CHAT_MEMBERS", 122, 195);
    public static final kfc X2 = new kfc("NOTIF_MESSAGE", 123, 128, bkb.a);
    public static final kfc Y2 = new kfc("NOTIF_TYPING", 124, 129);
    public static final kfc Z2 = new kfc("NOTIF_MARK", 125, 130, gp0.l);
    public static final kfc a3 = new kfc("NOTIF_CONTACT", 126, 131);
    public static final kfc b3 = new kfc("NOTIF_PRESENCE", 127, 132);
    public static final kfc c3 = new kfc("NOTIF_CONFIG", np0.m, 134);
    public static final kfc d3 = new kfc("NOTIF_CHAT", 129, 135);
    public static final kfc e3 = new kfc("NOTIF_ATTACH", 130, 136, ghb.j);
    public static final kfc f3 = new kfc("NOTIF_CALL_START", 131, 137);
    public static final kfc g3 = new kfc("NOTIF_CONTACT_SORT", 132, 139);
    public static final kfc h3 = new kfc("NOTIF_MSG_DELETE_RANGE", 133, 140);
    public static final kfc i3 = new kfc("NOTIF_MSG_DELETE", 134, 142, xvc.k);
    public static final kfc j3 = new kfc("NOTIF_MSG_REACTIONS_CHANGED", 135, 155);
    public static final kfc k3 = new kfc("NOTIF_MSG_YOU_REACTED", 136, 156);
    public static final kfc l3 = new kfc("NOTIF_CALLBACK_ANSWER", 137, 143);
    public static final kfc m3 = new kfc("CHAT_BOT_COMMANDS", 138, 144);
    public static final kfc n3 = new kfc("BOT_INFO", 139, 145, ku6.d);
    public static final kfc o3 = new kfc("NOTIF_LOCATION", 140, 147);
    public static final kfc p3 = new kfc("NOTIF_LOCATION_REQUEST", 141, 148);
    public static final kfc q3 = new kfc("NOTIF_ASSETS_UPDATE", 142, 150);
    public static final kfc r3 = new kfc("CHAT_HIDE", 143, 196);
    public static final kfc s3 = new kfc("CHAT_SEARCH_COMMON_PARTICIPANTS", 144, 198);
    public static final kfc t3 = new kfc("NOTIF_MSG_DELAYED", 145, 154, ku6.k);
    public static final kfc u3 = new kfc("NOTIF_PROFILE", 146, 159, a8g.m);
    public static final kfc v3 = new kfc("PROFILE_DELETE", 147, 199, j85.l);
    public static final kfc w3 = new kfc("PROFILE_DELETE_TIME", 148, 200, cy5.j);
    public static final kfc x3 = new kfc("WEB_APP_INIT_DATA", 149, 160, lhb.o);
    public static final kfc y3 = new kfc("COMPLAIN", 150, 161, ghb.e);
    public static final kfc z3 = new kfc("COMPLAIN_REASONS_GET", 151, 162, khb.e);
    public static final kfc A3 = new kfc("CALL_HISTORY", 152, 163, j85.d);
    public static final kfc B3 = new kfc("CALL_HISTORY_CLEAR", 153, 164, a8g.e);
    public static final kfc C3 = new kfc("NOTIF_CALL_HISTORY", 154, 165, lhb.j);
    public static final kfc D3 = new kfc("FOLDERS_GET", 155, 272, xvc.h);
    public static final kfc E3 = new kfc("FOLDERS_GET_BY_ID", 156, 273, ku6.h);
    public static final kfc F3 = new kfc("FOLDERS_UPDATE", 157, 274, j85.h);
    public static final kfc G3 = new kfc("FOLDERS_REORDER", 158, 275, a8g.j);
    public static final kfc H3 = new kfc("FOLDERS_DELETE", 159, 276, gp0.i);
    public static final kfc I3 = new kfc("NOTIF_FOLDERS", 160, 277, nhb.j);

    static {
        khb khbVar = khb.i;
        J3 = new kfc("AUTH_QR_APPROVE", 161, (short) 290, khbVar);
        K3 = new kfc("NOTIF_BANNERS", 162, (short) 292, khbVar);
        L3 = new kfc("BANNERS_GET", 163, (short) 302, gp0.b);
        M3 = new kfc("CHAT_SUGGEST", 164, (short) 300, cy5.c);
        N3 = new kfc("AUDIO_PLAY", 165, (short) 301, ku6.c);
        O3 = new kfc("MSG_DELIVERY", 166, (short) 303, me0.e);
        P3 = new kfc("SEND_VOTE", 167, (short) 304, gp0.m);
        Q3 = new kfc("VOTERS_LIST_BY_ANSWER", 168, (short) 305, ku6.l);
        R3 = new kfc("GET_POLL_UPDATES", 169, (short) 306, lhb.i);
        S3 = new kfc("TRANSCRIBE_MEDIA", 170, (short) 202, l0i.a);
        T3 = new kfc("NOTIF_TRANSCRIPTION", 171, (short) 293, ukb.a);
        U3 = new kfc("ORG_INFO", 172, (short) 256, khb.j);
        V3 = new kfc("CHAT_LIVESTREAM_INFO", 173, (short) 62, gp0.e);
        W3 = new kfc("PHOTO_URL_REFRESH", 174, (short) 203, lhb.k);
        X3 = new kfc("MSG_DELETE_USER", 175, (short) 94, ghb.i);
        kfc[] kfcVarArr = {f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, X, Y, Z, n1, o1, p1, q1, r1, s1, t1, u1, v1, w1, x1, y1, z1, A1, B1, C1, D1, E1, F1, G1, H1, I1, J1, K1, L1, M1, N1, O1, P1, Q1, R1, S1, T1, U1, V1, W1, X1, Y1, Z1, a2, b2, c2, d2, e2, f2, g2, h2, i2, j2, k2, l2, m2, n2, o2, p2, q2, r2, s2, t2, u2, v2, w2, x2, y2, z2, A2, B2, C2, D2, E2, F2, G2, H2, I2, J2, K2, L2, M2, N2, O2, P2, Q2, R2, S2, T2, U2, V2, W2, X2, Y2, Z2, a3, b3, c3, d3, e3, f3, g3, h3, i3, j3, k3, l3, m3, n3, o3, p3, q3, r3, s3, t3, u3, v3, w3, x3, y3, z3, A3, B3, C3, D3, E3, F3, G3, H3, I3, J3, K3, L3, M3, N3, O3, P3, Q3, R3, S3, T3, U3, V3, W3, X3};
        Y3 = kfcVarArr;
        Z3 = cqk.n(kfcVarArr);
        c = new lhb(21);
        d = new HashMap();
        e = new HashMap();
        for (kfc kfcVar : Z3) {
            d.put(Short.valueOf(kfcVar.a), kfcVar.name());
            HashMap map = e;
            Short shValueOf = Short.valueOf(kfcVar.a);
            String strName = kfcVar.name();
            lhb lhbVar = c;
            short s4 = kfcVar.a;
            lhbVar.getClass();
            map.put(shValueOf, nbh.v(strName, "(0x", Integer.toHexString(s4 & 65535), ")"));
        }
    }

    public kfc(String str, int i4, short s4, fu3 fu3Var) {
        super(str, i4);
        this.a = s4;
        this.b = fu3Var;
    }

    public static kfc valueOf(String str) {
        return (kfc) Enum.valueOf(kfc.class, str);
    }

    public static kfc[] values() {
        return (kfc[]) Y3.clone();
    }

    public /* synthetic */ kfc(String str, int i4, short s4) {
        this(str, i4, s4, null);
    }
}
