package defpackage;

import com.vk.push.core.base.AidlException;
import java.io.IOException;
import java.util.HashMap;

/* JADX INFO: loaded from: classes2.dex */
final class lol implements zpb {
    private static final jp6 A;
    private static final jp6 A0;
    private static final jp6 B;
    private static final jp6 B0;
    private static final jp6 C;
    private static final jp6 C0;
    private static final jp6 D;
    private static final jp6 D0;
    private static final jp6 E;
    private static final jp6 E0;
    private static final jp6 F;
    private static final jp6 F0;
    private static final jp6 G;
    private static final jp6 G0;
    private static final jp6 H;
    private static final jp6 H0;
    private static final jp6 I;
    private static final jp6 I0;
    private static final jp6 J;
    private static final jp6 J0;
    private static final jp6 K;
    private static final jp6 K0;
    private static final jp6 L;
    private static final jp6 L0;
    private static final jp6 M;
    private static final jp6 M0;
    private static final jp6 N;
    private static final jp6 N0;
    private static final jp6 O;
    private static final jp6 O0;
    private static final jp6 P;
    private static final jp6 P0;
    private static final jp6 Q;
    private static final jp6 Q0;
    private static final jp6 R;
    private static final jp6 R0;
    private static final jp6 S;
    private static final jp6 S0;
    private static final jp6 T;
    private static final jp6 T0;
    private static final jp6 U;
    private static final jp6 U0;
    private static final jp6 V;
    private static final jp6 V0;
    private static final jp6 W;
    private static final jp6 W0;
    private static final jp6 X;
    private static final jp6 X0;
    private static final jp6 Y;
    private static final jp6 Y0;
    private static final jp6 Z;
    private static final jp6 Z0;
    static final lol a = new lol();
    private static final jp6 a0;
    private static final jp6 a1;
    private static final jp6 b;
    private static final jp6 b0;
    private static final jp6 b1;
    private static final jp6 c;
    private static final jp6 c0;
    private static final jp6 c1;
    private static final jp6 d;
    private static final jp6 d0;
    private static final jp6 d1;
    private static final jp6 e;
    private static final jp6 e0;
    private static final jp6 e1;
    private static final jp6 f;
    private static final jp6 f0;
    private static final jp6 f1;
    private static final jp6 g;
    private static final jp6 g0;
    private static final jp6 g1;
    private static final jp6 h;
    private static final jp6 h0;
    private static final jp6 h1;
    private static final jp6 i;
    private static final jp6 i0;
    private static final jp6 i1;
    private static final jp6 j;
    private static final jp6 j0;
    private static final jp6 j1;
    private static final jp6 k;
    private static final jp6 k0;
    private static final jp6 k1;
    private static final jp6 l;
    private static final jp6 l0;
    private static final jp6 l1;
    private static final jp6 m;
    private static final jp6 m0;
    private static final jp6 m1;
    private static final jp6 n;
    private static final jp6 n0;
    private static final jp6 n1;
    private static final jp6 o;
    private static final jp6 o0;
    private static final jp6 o1;
    private static final jp6 p;
    private static final jp6 p0;
    private static final jp6 p1;
    private static final jp6 q;
    private static final jp6 q0;
    private static final jp6 q1;
    private static final jp6 r;
    private static final jp6 r0;
    private static final jp6 r1;
    private static final jp6 s;
    private static final jp6 s0;
    private static final jp6 s1;
    private static final jp6 t;
    private static final jp6 t0;
    private static final jp6 t1;
    private static final jp6 u;
    private static final jp6 u0;
    private static final jp6 u1;
    private static final jp6 v;
    private static final jp6 v0;
    private static final jp6 v1;
    private static final jp6 w;
    private static final jp6 w0;
    private static final jp6 w1;
    private static final jp6 x;
    private static final jp6 x0;
    private static final jp6 x1;
    private static final jp6 y;
    private static final jp6 y0;
    private static final jp6 y1;
    private static final jp6 z;
    private static final jp6 z0;

    static {
        d6l d6lVarK = ewi.k(1);
        HashMap map = new HashMap();
        map.put(d6lVarK.annotationType(), d6lVarK);
        b = new jp6("systemInfo", p.h(map));
        d6l d6lVarK2 = ewi.k(2);
        HashMap map2 = new HashMap();
        map2.put(d6lVarK2.annotationType(), d6lVarK2);
        c = new jp6("eventName", p.h(map2));
        d6l d6lVarK3 = ewi.k(37);
        HashMap map3 = new HashMap();
        map3.put(d6lVarK3.annotationType(), d6lVarK3);
        d = new jp6("isThickClient", p.h(map3));
        d6l d6lVarK4 = ewi.k(61);
        HashMap map4 = new HashMap();
        map4.put(d6lVarK4.annotationType(), d6lVarK4);
        e = new jp6("clientType", p.h(map4));
        d6l d6lVarK5 = ewi.k(3);
        HashMap map5 = new HashMap();
        map5.put(d6lVarK5.annotationType(), d6lVarK5);
        f = new jp6("modelDownloadLogEvent", p.h(map5));
        d6l d6lVarK6 = ewi.k(20);
        HashMap map6 = new HashMap();
        map6.put(d6lVarK6.annotationType(), d6lVarK6);
        g = new jp6("customModelLoadLogEvent", p.h(map6));
        d6l d6lVarK7 = ewi.k(4);
        HashMap map7 = new HashMap();
        map7.put(d6lVarK7.annotationType(), d6lVarK7);
        h = new jp6("customModelInferenceLogEvent", p.h(map7));
        d6l d6lVarK8 = ewi.k(29);
        HashMap map8 = new HashMap();
        map8.put(d6lVarK8.annotationType(), d6lVarK8);
        i = new jp6("customModelCreateLogEvent", p.h(map8));
        d6l d6lVarK9 = ewi.k(5);
        HashMap map9 = new HashMap();
        map9.put(d6lVarK9.annotationType(), d6lVarK9);
        j = new jp6("onDeviceFaceDetectionLogEvent", p.h(map9));
        d6l d6lVarK10 = ewi.k(59);
        HashMap map10 = new HashMap();
        map10.put(d6lVarK10.annotationType(), d6lVarK10);
        k = new jp6("onDeviceFaceLoadLogEvent", p.h(map10));
        d6l d6lVarK11 = ewi.k(6);
        HashMap map11 = new HashMap();
        map11.put(d6lVarK11.annotationType(), d6lVarK11);
        l = new jp6("onDeviceTextDetectionLogEvent", p.h(map11));
        d6l d6lVarK12 = ewi.k(79);
        HashMap map12 = new HashMap();
        map12.put(d6lVarK12.annotationType(), d6lVarK12);
        m = new jp6("onDeviceTextDetectionLoadLogEvent", p.h(map12));
        d6l d6lVarK13 = ewi.k(7);
        HashMap map13 = new HashMap();
        map13.put(d6lVarK13.annotationType(), d6lVarK13);
        n = new jp6("onDeviceBarcodeDetectionLogEvent", p.h(map13));
        d6l d6lVarK14 = ewi.k(58);
        HashMap map14 = new HashMap();
        map14.put(d6lVarK14.annotationType(), d6lVarK14);
        o = new jp6("onDeviceBarcodeLoadLogEvent", p.h(map14));
        d6l d6lVarK15 = ewi.k(48);
        HashMap map15 = new HashMap();
        map15.put(d6lVarK15.annotationType(), d6lVarK15);
        p = new jp6("onDeviceImageLabelCreateLogEvent", p.h(map15));
        d6l d6lVarK16 = ewi.k(49);
        HashMap map16 = new HashMap();
        map16.put(d6lVarK16.annotationType(), d6lVarK16);
        q = new jp6("onDeviceImageLabelLoadLogEvent", p.h(map16));
        d6l d6lVarK17 = ewi.k(18);
        HashMap map17 = new HashMap();
        map17.put(d6lVarK17.annotationType(), d6lVarK17);
        r = new jp6("onDeviceImageLabelDetectionLogEvent", p.h(map17));
        d6l d6lVarK18 = ewi.k(26);
        HashMap map18 = new HashMap();
        map18.put(d6lVarK18.annotationType(), d6lVarK18);
        s = new jp6("onDeviceObjectCreateLogEvent", p.h(map18));
        d6l d6lVarK19 = ewi.k(27);
        HashMap map19 = new HashMap();
        map19.put(d6lVarK19.annotationType(), d6lVarK19);
        t = new jp6("onDeviceObjectLoadLogEvent", p.h(map19));
        d6l d6lVarK20 = ewi.k(28);
        HashMap map20 = new HashMap();
        map20.put(d6lVarK20.annotationType(), d6lVarK20);
        u = new jp6("onDeviceObjectInferenceLogEvent", p.h(map20));
        d6l d6lVarK21 = ewi.k(44);
        HashMap map21 = new HashMap();
        map21.put(d6lVarK21.annotationType(), d6lVarK21);
        v = new jp6("onDevicePoseDetectionLogEvent", p.h(map21));
        d6l d6lVarK22 = ewi.k(45);
        HashMap map22 = new HashMap();
        map22.put(d6lVarK22.annotationType(), d6lVarK22);
        w = new jp6("onDeviceSegmentationLogEvent", p.h(map22));
        d6l d6lVarK23 = ewi.k(19);
        HashMap map23 = new HashMap();
        map23.put(d6lVarK23.annotationType(), d6lVarK23);
        x = new jp6("onDeviceSmartReplyLogEvent", p.h(map23));
        d6l d6lVarK24 = ewi.k(21);
        HashMap map24 = new HashMap();
        map24.put(d6lVarK24.annotationType(), d6lVarK24);
        y = new jp6("onDeviceLanguageIdentificationLogEvent", p.h(map24));
        d6l d6lVarK25 = ewi.k(22);
        HashMap map25 = new HashMap();
        map25.put(d6lVarK25.annotationType(), d6lVarK25);
        z = new jp6("onDeviceTranslationLogEvent", p.h(map25));
        d6l d6lVarK26 = ewi.k(8);
        HashMap map26 = new HashMap();
        map26.put(d6lVarK26.annotationType(), d6lVarK26);
        A = new jp6("cloudFaceDetectionLogEvent", p.h(map26));
        d6l d6lVarK27 = ewi.k(9);
        HashMap map27 = new HashMap();
        map27.put(d6lVarK27.annotationType(), d6lVarK27);
        B = new jp6("cloudCropHintDetectionLogEvent", p.h(map27));
        d6l d6lVarK28 = ewi.k(10);
        HashMap map28 = new HashMap();
        map28.put(d6lVarK28.annotationType(), d6lVarK28);
        C = new jp6("cloudDocumentTextDetectionLogEvent", p.h(map28));
        d6l d6lVarK29 = ewi.k(11);
        HashMap map29 = new HashMap();
        map29.put(d6lVarK29.annotationType(), d6lVarK29);
        D = new jp6("cloudImagePropertiesDetectionLogEvent", p.h(map29));
        d6l d6lVarK30 = ewi.k(12);
        HashMap map30 = new HashMap();
        map30.put(d6lVarK30.annotationType(), d6lVarK30);
        E = new jp6("cloudImageLabelDetectionLogEvent", p.h(map30));
        d6l d6lVarK31 = ewi.k(13);
        HashMap map31 = new HashMap();
        map31.put(d6lVarK31.annotationType(), d6lVarK31);
        F = new jp6("cloudLandmarkDetectionLogEvent", p.h(map31));
        d6l d6lVarK32 = ewi.k(14);
        HashMap map32 = new HashMap();
        map32.put(d6lVarK32.annotationType(), d6lVarK32);
        G = new jp6("cloudLogoDetectionLogEvent", p.h(map32));
        d6l d6lVarK33 = ewi.k(15);
        HashMap map33 = new HashMap();
        map33.put(d6lVarK33.annotationType(), d6lVarK33);
        H = new jp6("cloudSafeSearchDetectionLogEvent", p.h(map33));
        d6l d6lVarK34 = ewi.k(16);
        HashMap map34 = new HashMap();
        map34.put(d6lVarK34.annotationType(), d6lVarK34);
        I = new jp6("cloudTextDetectionLogEvent", p.h(map34));
        d6l d6lVarK35 = ewi.k(17);
        HashMap map35 = new HashMap();
        map35.put(d6lVarK35.annotationType(), d6lVarK35);
        J = new jp6("cloudWebSearchDetectionLogEvent", p.h(map35));
        d6l d6lVarK36 = ewi.k(23);
        HashMap map36 = new HashMap();
        map36.put(d6lVarK36.annotationType(), d6lVarK36);
        K = new jp6("automlImageLabelingCreateLogEvent", p.h(map36));
        d6l d6lVarK37 = ewi.k(24);
        HashMap map37 = new HashMap();
        map37.put(d6lVarK37.annotationType(), d6lVarK37);
        L = new jp6("automlImageLabelingLoadLogEvent", p.h(map37));
        d6l d6lVarK38 = ewi.k(25);
        HashMap map38 = new HashMap();
        map38.put(d6lVarK38.annotationType(), d6lVarK38);
        M = new jp6("automlImageLabelingInferenceLogEvent", p.h(map38));
        d6l d6lVarK39 = ewi.k(39);
        HashMap map39 = new HashMap();
        map39.put(d6lVarK39.annotationType(), d6lVarK39);
        N = new jp6("isModelDownloadedLogEvent", p.h(map39));
        d6l d6lVarK40 = ewi.k(40);
        HashMap map40 = new HashMap();
        map40.put(d6lVarK40.annotationType(), d6lVarK40);
        O = new jp6("deleteModelLogEvent", p.h(map40));
        d6l d6lVarK41 = ewi.k(30);
        HashMap map41 = new HashMap();
        map41.put(d6lVarK41.annotationType(), d6lVarK41);
        P = new jp6("aggregatedAutomlImageLabelingInferenceLogEvent", p.h(map41));
        d6l d6lVarK42 = ewi.k(31);
        HashMap map42 = new HashMap();
        map42.put(d6lVarK42.annotationType(), d6lVarK42);
        Q = new jp6("aggregatedCustomModelInferenceLogEvent", p.h(map42));
        d6l d6lVarK43 = ewi.k(32);
        HashMap map43 = new HashMap();
        map43.put(d6lVarK43.annotationType(), d6lVarK43);
        R = new jp6("aggregatedOnDeviceFaceDetectionLogEvent", p.h(map43));
        d6l d6lVarK44 = ewi.k(33);
        HashMap map44 = new HashMap();
        map44.put(d6lVarK44.annotationType(), d6lVarK44);
        S = new jp6("aggregatedOnDeviceBarcodeDetectionLogEvent", p.h(map44));
        d6l d6lVarK45 = ewi.k(34);
        HashMap map45 = new HashMap();
        map45.put(d6lVarK45.annotationType(), d6lVarK45);
        T = new jp6("aggregatedOnDeviceImageLabelDetectionLogEvent", p.h(map45));
        d6l d6lVarK46 = ewi.k(35);
        HashMap map46 = new HashMap();
        map46.put(d6lVarK46.annotationType(), d6lVarK46);
        U = new jp6("aggregatedOnDeviceObjectInferenceLogEvent", p.h(map46));
        d6l d6lVarK47 = ewi.k(36);
        HashMap map47 = new HashMap();
        map47.put(d6lVarK47.annotationType(), d6lVarK47);
        V = new jp6("aggregatedOnDeviceTextDetectionLogEvent", p.h(map47));
        d6l d6lVarK48 = ewi.k(46);
        HashMap map48 = new HashMap();
        map48.put(d6lVarK48.annotationType(), d6lVarK48);
        W = new jp6("aggregatedOnDevicePoseDetectionLogEvent", p.h(map48));
        d6l d6lVarK49 = ewi.k(47);
        HashMap map49 = new HashMap();
        map49.put(d6lVarK49.annotationType(), d6lVarK49);
        X = new jp6("aggregatedOnDeviceSegmentationLogEvent", p.h(map49));
        d6l d6lVarK50 = ewi.k(69);
        HashMap map50 = new HashMap();
        map50.put(d6lVarK50.annotationType(), d6lVarK50);
        Y = new jp6("pipelineAccelerationInferenceEvents", p.h(map50));
        d6l d6lVarK51 = ewi.k(42);
        HashMap map51 = new HashMap();
        map51.put(d6lVarK51.annotationType(), d6lVarK51);
        Z = new jp6("remoteConfigLogEvent", p.h(map51));
        d6l d6lVarK52 = ewi.k(50);
        HashMap map52 = new HashMap();
        map52.put(d6lVarK52.annotationType(), d6lVarK52);
        a0 = new jp6("inputImageConstructionLogEvent", p.h(map52));
        d6l d6lVarK53 = ewi.k(51);
        HashMap map53 = new HashMap();
        map53.put(d6lVarK53.annotationType(), d6lVarK53);
        b0 = new jp6("leakedHandleEvent", p.h(map53));
        d6l d6lVarK54 = ewi.k(52);
        HashMap map54 = new HashMap();
        map54.put(d6lVarK54.annotationType(), d6lVarK54);
        c0 = new jp6("cameraSourceLogEvent", p.h(map54));
        d6l d6lVarK55 = ewi.k(53);
        HashMap map55 = new HashMap();
        map55.put(d6lVarK55.annotationType(), d6lVarK55);
        d0 = new jp6("imageLabelOptionalModuleLogEvent", p.h(map55));
        d6l d6lVarK56 = ewi.k(54);
        HashMap map56 = new HashMap();
        map56.put(d6lVarK56.annotationType(), d6lVarK56);
        e0 = new jp6("languageIdentificationOptionalModuleLogEvent", p.h(map56));
        d6l d6lVarK57 = ewi.k(60);
        HashMap map57 = new HashMap();
        map57.put(d6lVarK57.annotationType(), d6lVarK57);
        f0 = new jp6("faceDetectionOptionalModuleLogEvent", p.h(map57));
        d6l d6lVarK58 = ewi.k(85);
        HashMap map58 = new HashMap();
        map58.put(d6lVarK58.annotationType(), d6lVarK58);
        g0 = new jp6("documentDetectionOptionalModuleLogEvent", p.h(map58));
        d6l d6lVarK59 = ewi.k(86);
        HashMap map59 = new HashMap();
        map59.put(d6lVarK59.annotationType(), d6lVarK59);
        h0 = new jp6("documentCroppingOptionalModuleLogEvent", p.h(map59));
        d6l d6lVarK60 = ewi.k(87);
        HashMap map60 = new HashMap();
        map60.put(d6lVarK60.annotationType(), d6lVarK60);
        i0 = new jp6("documentEnhancementOptionalModuleLogEvent", p.h(map60));
        d6l d6lVarK61 = ewi.k(55);
        HashMap map61 = new HashMap();
        map61.put(d6lVarK61.annotationType(), d6lVarK61);
        j0 = new jp6("nlClassifierOptionalModuleLogEvent", p.h(map61));
        d6l d6lVarK62 = ewi.k(56);
        HashMap map62 = new HashMap();
        map62.put(d6lVarK62.annotationType(), d6lVarK62);
        k0 = new jp6("nlClassifierClientLibraryLogEvent", p.h(map62));
        d6l d6lVarK63 = ewi.k(57);
        HashMap map63 = new HashMap();
        map63.put(d6lVarK63.annotationType(), d6lVarK63);
        l0 = new jp6("accelerationAllowlistLogEvent", p.h(map63));
        d6l d6lVarK64 = ewi.k(62);
        HashMap map64 = new HashMap();
        map64.put(d6lVarK64.annotationType(), d6lVarK64);
        m0 = new jp6("toxicityDetectionCreateEvent", p.h(map64));
        d6l d6lVarK65 = ewi.k(63);
        HashMap map65 = new HashMap();
        map65.put(d6lVarK65.annotationType(), d6lVarK65);
        n0 = new jp6("toxicityDetectionLoadEvent", p.h(map65));
        d6l d6lVarK66 = ewi.k(64);
        HashMap map66 = new HashMap();
        map66.put(d6lVarK66.annotationType(), d6lVarK66);
        o0 = new jp6("toxicityDetectionInferenceEvent", p.h(map66));
        d6l d6lVarK67 = ewi.k(65);
        HashMap map67 = new HashMap();
        map67.put(d6lVarK67.annotationType(), d6lVarK67);
        p0 = new jp6("barcodeDetectionOptionalModuleLogEvent", p.h(map67));
        d6l d6lVarK68 = ewi.k(66);
        HashMap map68 = new HashMap();
        map68.put(d6lVarK68.annotationType(), d6lVarK68);
        q0 = new jp6("customImageLabelOptionalModuleLogEvent", p.h(map68));
        d6l d6lVarK69 = ewi.k(67);
        HashMap map69 = new HashMap();
        map69.put(d6lVarK69.annotationType(), d6lVarK69);
        r0 = new jp6("codeScannerScanApiEvent", p.h(map69));
        d6l d6lVarK70 = ewi.k(68);
        HashMap map70 = new HashMap();
        map70.put(d6lVarK70.annotationType(), d6lVarK70);
        s0 = new jp6("codeScannerOptionalModuleEvent", p.h(map70));
        d6l d6lVarK71 = ewi.k(70);
        HashMap map71 = new HashMap();
        map71.put(d6lVarK71.annotationType(), d6lVarK71);
        t0 = new jp6("onDeviceExplicitContentCreateLogEvent", p.h(map71));
        d6l d6lVarK72 = ewi.k(71);
        HashMap map72 = new HashMap();
        map72.put(d6lVarK72.annotationType(), d6lVarK72);
        u0 = new jp6("onDeviceExplicitContentLoadLogEvent", p.h(map72));
        d6l d6lVarK73 = ewi.k(72);
        HashMap map73 = new HashMap();
        map73.put(d6lVarK73.annotationType(), d6lVarK73);
        v0 = new jp6("onDeviceExplicitContentInferenceLogEvent", p.h(map73));
        d6l d6lVarK74 = ewi.k(73);
        HashMap map74 = new HashMap();
        map74.put(d6lVarK74.annotationType(), d6lVarK74);
        w0 = new jp6("aggregatedOnDeviceExplicitContentLogEvent", p.h(map74));
        d6l d6lVarK75 = ewi.k(74);
        HashMap map75 = new HashMap();
        map75.put(d6lVarK75.annotationType(), d6lVarK75);
        x0 = new jp6("onDeviceFaceMeshCreateLogEvent", p.h(map75));
        d6l d6lVarK76 = ewi.k(75);
        HashMap map76 = new HashMap();
        map76.put(d6lVarK76.annotationType(), d6lVarK76);
        y0 = new jp6("onDeviceFaceMeshLoadLogEvent", p.h(map76));
        d6l d6lVarK77 = ewi.k(76);
        HashMap map77 = new HashMap();
        map77.put(d6lVarK77.annotationType(), d6lVarK77);
        z0 = new jp6("onDeviceFaceMeshLogEvent", p.h(map77));
        d6l d6lVarK78 = ewi.k(77);
        HashMap map78 = new HashMap();
        map78.put(d6lVarK78.annotationType(), d6lVarK78);
        A0 = new jp6("aggregatedOnDeviceFaceMeshLogEvent", p.h(map78));
        d6l d6lVarK79 = ewi.k(78);
        HashMap map79 = new HashMap();
        map79.put(d6lVarK79.annotationType(), d6lVarK79);
        B0 = new jp6("smartReplyOptionalModuleLogEvent", p.h(map79));
        d6l d6lVarK80 = ewi.k(80);
        HashMap map80 = new HashMap();
        map80.put(d6lVarK80.annotationType(), d6lVarK80);
        C0 = new jp6("textDetectionOptionalModuleLogEvent", p.h(map80));
        d6l d6lVarK81 = ewi.k(81);
        HashMap map81 = new HashMap();
        map81.put(d6lVarK81.annotationType(), d6lVarK81);
        D0 = new jp6("onDeviceImageQualityAnalysisCreateLogEvent", p.h(map81));
        d6l d6lVarK82 = ewi.k(82);
        HashMap map82 = new HashMap();
        map82.put(d6lVarK82.annotationType(), d6lVarK82);
        E0 = new jp6("onDeviceImageQualityAnalysisLoadLogEvent", p.h(map82));
        d6l d6lVarK83 = ewi.k(83);
        HashMap map83 = new HashMap();
        map83.put(d6lVarK83.annotationType(), d6lVarK83);
        F0 = new jp6("onDeviceImageQualityAnalysisLogEvent", p.h(map83));
        d6l d6lVarK84 = ewi.k(84);
        HashMap map84 = new HashMap();
        map84.put(d6lVarK84.annotationType(), d6lVarK84);
        G0 = new jp6("aggregatedOnDeviceImageQualityAnalysisLogEvent", p.h(map84));
        d6l d6lVarK85 = ewi.k(88);
        HashMap map85 = new HashMap();
        map85.put(d6lVarK85.annotationType(), d6lVarK85);
        H0 = new jp6("imageQualityAnalysisOptionalModuleLogEvent", p.h(map85));
        d6l d6lVarK86 = ewi.k(89);
        HashMap map86 = new HashMap();
        map86.put(d6lVarK86.annotationType(), d6lVarK86);
        I0 = new jp6("imageCaptioningOptionalModuleLogEvent", p.h(map86));
        d6l d6lVarK87 = ewi.k(90);
        HashMap map87 = new HashMap();
        map87.put(d6lVarK87.annotationType(), d6lVarK87);
        J0 = new jp6("onDeviceImageCaptioningCreateLogEvent", p.h(map87));
        d6l d6lVarK88 = ewi.k(91);
        HashMap map88 = new HashMap();
        map88.put(d6lVarK88.annotationType(), d6lVarK88);
        K0 = new jp6("onDeviceImageCaptioningLoadLogEvent", p.h(map88));
        d6l d6lVarK89 = ewi.k(92);
        HashMap map89 = new HashMap();
        map89.put(d6lVarK89.annotationType(), d6lVarK89);
        L0 = new jp6("onDeviceImageCaptioningInferenceLogEvent", p.h(map89));
        d6l d6lVarK90 = ewi.k(93);
        HashMap map90 = new HashMap();
        map90.put(d6lVarK90.annotationType(), d6lVarK90);
        M0 = new jp6("aggregatedOnDeviceImageCaptioningInferenceLogEvent", p.h(map90));
        d6l d6lVarK91 = ewi.k(94);
        HashMap map91 = new HashMap();
        map91.put(d6lVarK91.annotationType(), d6lVarK91);
        N0 = new jp6("onDeviceDocumentDetectionCreateLogEvent", p.h(map91));
        d6l d6lVarK92 = ewi.k(95);
        HashMap map92 = new HashMap();
        map92.put(d6lVarK92.annotationType(), d6lVarK92);
        O0 = new jp6("onDeviceDocumentDetectionLoadLogEvent", p.h(map92));
        d6l d6lVarK93 = ewi.k(96);
        HashMap map93 = new HashMap();
        map93.put(d6lVarK93.annotationType(), d6lVarK93);
        P0 = new jp6("onDeviceDocumentDetectionLogEvent", p.h(map93));
        d6l d6lVarK94 = ewi.k(97);
        HashMap map94 = new HashMap();
        map94.put(d6lVarK94.annotationType(), d6lVarK94);
        Q0 = new jp6("aggregatedOnDeviceDocumentDetectionLogEvent", p.h(map94));
        d6l d6lVarK95 = ewi.k(98);
        HashMap map95 = new HashMap();
        map95.put(d6lVarK95.annotationType(), d6lVarK95);
        R0 = new jp6("onDeviceDocumentCroppingCreateLogEvent", p.h(map95));
        d6l d6lVarK96 = ewi.k(99);
        HashMap map96 = new HashMap();
        map96.put(d6lVarK96.annotationType(), d6lVarK96);
        S0 = new jp6("onDeviceDocumentCroppingLoadLogEvent", p.h(map96));
        d6l d6lVarK97 = ewi.k(100);
        HashMap map97 = new HashMap();
        map97.put(d6lVarK97.annotationType(), d6lVarK97);
        T0 = new jp6("onDeviceDocumentCroppingLogEvent", p.h(map97));
        d6l d6lVarK98 = ewi.k(101);
        HashMap map98 = new HashMap();
        map98.put(d6lVarK98.annotationType(), d6lVarK98);
        U0 = new jp6("aggregatedOnDeviceDocumentCroppingLogEvent", p.h(map98));
        d6l d6lVarK99 = ewi.k(102);
        HashMap map99 = new HashMap();
        map99.put(d6lVarK99.annotationType(), d6lVarK99);
        V0 = new jp6("onDeviceDocumentEnhancementCreateLogEvent", p.h(map99));
        d6l d6lVarK100 = ewi.k(AidlException.HOST_IS_NOT_MASTER);
        HashMap map100 = new HashMap();
        map100.put(d6lVarK100.annotationType(), d6lVarK100);
        W0 = new jp6("onDeviceDocumentEnhancementLoadLogEvent", p.h(map100));
        d6l d6lVarK101 = ewi.k(AidlException.SDK_IS_NOT_INITIALIZED);
        HashMap map101 = new HashMap();
        map101.put(d6lVarK101.annotationType(), d6lVarK101);
        X0 = new jp6("onDeviceDocumentEnhancementLogEvent", p.h(map101));
        d6l d6lVarK102 = ewi.k(AidlException.TRANSFERRED_IPC_DATA_EXCEPTION);
        HashMap map102 = new HashMap();
        map102.put(d6lVarK102.annotationType(), d6lVarK102);
        Y0 = new jp6("aggregatedOnDeviceDocumentEnhancementLogEvent", p.h(map102));
        d6l d6lVarK103 = ewi.k(106);
        HashMap map103 = new HashMap();
        map103.put(d6lVarK103.annotationType(), d6lVarK103);
        Z0 = new jp6("scannerAutoZoomEvent", p.h(map103));
        d6l d6lVarK104 = ewi.k(107);
        HashMap map104 = new HashMap();
        map104.put(d6lVarK104.annotationType(), d6lVarK104);
        a1 = new jp6("lowLightAutoExposureComputationEvent", p.h(map104));
        d6l d6lVarK105 = ewi.k(108);
        HashMap map105 = new HashMap();
        map105.put(d6lVarK105.annotationType(), d6lVarK105);
        b1 = new jp6("lowLightFrameProcessEvent", p.h(map105));
        d6l d6lVarK106 = ewi.k(109);
        HashMap map106 = new HashMap();
        map106.put(d6lVarK106.annotationType(), d6lVarK106);
        c1 = new jp6("lowLightSceneDetectionEvent", p.h(map106));
        d6l d6lVarK107 = ewi.k(110);
        HashMap map107 = new HashMap();
        map107.put(d6lVarK107.annotationType(), d6lVarK107);
        d1 = new jp6("onDeviceStainRemovalLogEvent", p.h(map107));
        d6l d6lVarK108 = ewi.k(111);
        HashMap map108 = new HashMap();
        map108.put(d6lVarK108.annotationType(), d6lVarK108);
        e1 = new jp6("aggregatedOnDeviceStainRemovalLogEvent", p.h(map108));
        f1 = kol.a(112, jp6.a("stainRemovalOptionalModuleLogEvent"));
        g1 = kol.a(113, jp6.a("onDeviceShadowRemovalLogEvent"));
        h1 = kol.a(114, jp6.a("aggregatedOnDeviceShadowRemovalLogEvent"));
        i1 = kol.a(115, jp6.a("shadowRemovalOptionalModuleLogEvent"));
        j1 = kol.a(116, jp6.a("onDeviceDigitalInkSegmentationLogEvent"));
        k1 = kol.a(117, jp6.a("onDeviceDocumentScannerStartLogEvent"));
        l1 = kol.a(118, jp6.a("onDeviceDocumentScannerFinishLogEvent"));
        m1 = kol.a(119, jp6.a("onDeviceDocumentScannerUiStartLogEvent"));
        n1 = kol.a(120, jp6.a("onDeviceDocumentScannerUiFinishLogEvent"));
        o1 = kol.a(121, jp6.a("documentScannerUiOptionalModuleSessionStartLogEvent"));
        p1 = kol.a(122, jp6.a("documentScannerUiOptionalModuleSessionFinishLogEvent"));
        q1 = kol.a(123, jp6.a("onDeviceDocumentScannerUiCreateLogEvent"));
        r1 = kol.a(124, jp6.a("onDeviceSubjectSegmentationCreateLogEvent"));
        s1 = kol.a(125, jp6.a("onDeviceSubjectSegmentationLoadLogEvent"));
        t1 = kol.a(126, jp6.a("onDeviceSubjectSegmentationInferenceLogEvent"));
        u1 = kol.a(127, jp6.a("aggregatedOnDeviceSubjectSegmentationLogEvent"));
        v1 = kol.a(np0.m, jp6.a("subjectSegmentationOptionalModuleLogEvent"));
        w1 = kol.a(129, jp6.a("documentScannerUiModuleScreenViewEvent"));
        x1 = kol.a(130, jp6.a("documentScannerUiModuleScreenClickEvent"));
        y1 = kol.a(131, jp6.a("documentScannerUiModuleScreenErrorEvent"));
    }

    private lol() {
    }

    @Override // defpackage.v76
    public final /* bridge */ /* synthetic */ void a(Object obj, Object obj2) throws IOException {
        v3m v3mVar = (v3m) obj;
        aqb aqbVar = (aqb) obj2;
        aqbVar.a(b, v3mVar.g());
        aqbVar.a(c, v3mVar.c());
        aqbVar.a(d, null);
        aqbVar.a(e, v3mVar.b());
        aqbVar.a(f, null);
        aqbVar.a(g, null);
        aqbVar.a(h, null);
        aqbVar.a(i, null);
        aqbVar.a(j, null);
        aqbVar.a(k, null);
        aqbVar.a(l, null);
        aqbVar.a(m, null);
        aqbVar.a(n, v3mVar.d());
        aqbVar.a(o, v3mVar.e());
        aqbVar.a(p, null);
        aqbVar.a(q, null);
        aqbVar.a(r, null);
        aqbVar.a(s, null);
        aqbVar.a(t, null);
        aqbVar.a(u, null);
        aqbVar.a(v, null);
        aqbVar.a(w, null);
        aqbVar.a(x, null);
        aqbVar.a(y, null);
        aqbVar.a(z, null);
        aqbVar.a(A, null);
        aqbVar.a(B, null);
        aqbVar.a(C, null);
        aqbVar.a(D, null);
        aqbVar.a(E, null);
        aqbVar.a(F, null);
        aqbVar.a(G, null);
        aqbVar.a(H, null);
        aqbVar.a(I, null);
        aqbVar.a(J, null);
        aqbVar.a(K, null);
        aqbVar.a(L, null);
        aqbVar.a(M, null);
        aqbVar.a(N, null);
        aqbVar.a(O, null);
        aqbVar.a(P, null);
        aqbVar.a(Q, null);
        aqbVar.a(R, null);
        aqbVar.a(S, v3mVar.a());
        aqbVar.a(T, null);
        aqbVar.a(U, null);
        aqbVar.a(V, null);
        aqbVar.a(W, null);
        aqbVar.a(X, null);
        aqbVar.a(Y, null);
        aqbVar.a(Z, null);
        aqbVar.a(a0, null);
        aqbVar.a(b0, null);
        aqbVar.a(c0, null);
        aqbVar.a(d0, null);
        aqbVar.a(e0, null);
        aqbVar.a(f0, null);
        aqbVar.a(g0, null);
        aqbVar.a(h0, null);
        aqbVar.a(i0, null);
        aqbVar.a(j0, null);
        aqbVar.a(k0, null);
        aqbVar.a(l0, null);
        aqbVar.a(m0, null);
        aqbVar.a(n0, null);
        aqbVar.a(o0, null);
        aqbVar.a(p0, null);
        aqbVar.a(q0, null);
        aqbVar.a(r0, null);
        aqbVar.a(s0, null);
        aqbVar.a(t0, null);
        aqbVar.a(u0, null);
        aqbVar.a(v0, null);
        aqbVar.a(w0, null);
        aqbVar.a(x0, null);
        aqbVar.a(y0, null);
        aqbVar.a(z0, null);
        aqbVar.a(A0, null);
        aqbVar.a(B0, null);
        aqbVar.a(C0, null);
        aqbVar.a(D0, null);
        aqbVar.a(E0, null);
        aqbVar.a(F0, null);
        aqbVar.a(G0, null);
        aqbVar.a(H0, null);
        aqbVar.a(I0, null);
        aqbVar.a(J0, null);
        aqbVar.a(K0, null);
        aqbVar.a(L0, null);
        aqbVar.a(M0, null);
        aqbVar.a(N0, null);
        aqbVar.a(O0, null);
        aqbVar.a(P0, null);
        aqbVar.a(Q0, null);
        aqbVar.a(R0, null);
        aqbVar.a(S0, null);
        aqbVar.a(T0, null);
        aqbVar.a(U0, null);
        aqbVar.a(V0, null);
        aqbVar.a(W0, null);
        aqbVar.a(X0, null);
        aqbVar.a(Y0, null);
        aqbVar.a(Z0, v3mVar.f());
        aqbVar.a(a1, null);
        aqbVar.a(b1, null);
        aqbVar.a(c1, null);
        aqbVar.a(d1, null);
        aqbVar.a(e1, null);
        aqbVar.a(f1, null);
        aqbVar.a(g1, null);
        aqbVar.a(h1, null);
        aqbVar.a(i1, null);
        aqbVar.a(j1, null);
        aqbVar.a(k1, null);
        aqbVar.a(l1, null);
        aqbVar.a(m1, null);
        aqbVar.a(n1, null);
        aqbVar.a(o1, null);
        aqbVar.a(p1, null);
        aqbVar.a(q1, null);
        aqbVar.a(r1, null);
        aqbVar.a(s1, null);
        aqbVar.a(t1, null);
        aqbVar.a(u1, null);
        aqbVar.a(v1, null);
        aqbVar.a(w1, null);
        aqbVar.a(x1, null);
        aqbVar.a(y1, null);
    }
}
