package defpackage;

import com.vk.push.core.base.AidlException;
import org.apache.http.HttpStatus;

/* JADX INFO: loaded from: classes2.dex */
public enum n3m implements x5l {
    NO_ERROR(0),
    INCOMPATIBLE_INPUT(1),
    INCOMPATIBLE_OUTPUT(2),
    INCOMPATIBLE_TFLITE_VERSION(3),
    MISSING_OP(4),
    DATA_TYPE_ERROR(6),
    TFLITE_INTERNAL_ERROR(7),
    TFLITE_UNKNOWN_ERROR(8),
    MEDIAPIPE_ERROR(9),
    TIME_OUT_FETCHING_MODEL_METADATA(5),
    MODEL_NOT_DOWNLOADED(100),
    URI_EXPIRED(101),
    NO_NETWORK_CONNECTION(102),
    METERED_NETWORK(AidlException.HOST_IS_NOT_MASTER),
    DOWNLOAD_FAILED(AidlException.SDK_IS_NOT_INITIALIZED),
    MODEL_INFO_DOWNLOAD_UNSUCCESSFUL_HTTP_STATUS(AidlException.TRANSFERRED_IPC_DATA_EXCEPTION),
    MODEL_INFO_DOWNLOAD_NO_HASH(106),
    MODEL_INFO_DOWNLOAD_CONNECTION_FAILED(107),
    NO_VALID_MODEL(108),
    LOCAL_MODEL_INVALID(109),
    REMOTE_MODEL_INVALID(110),
    REMOTE_MODEL_LOADER_ERROR(111),
    REMOTE_MODEL_LOADER_LOADS_NO_MODEL(112),
    SMART_REPLY_LANG_ID_DETECTAION_FAILURE(113),
    MODEL_NOT_REGISTERED(114),
    MODEL_TYPE_MISUSE(115),
    MODEL_HASH_MISMATCH(116),
    OPTIONAL_MODULE_NOT_AVAILABLE(201),
    OPTIONAL_MODULE_INIT_ERROR(202),
    OPTIONAL_MODULE_INFERENCE_ERROR(203),
    OPTIONAL_MODULE_RELEASE_ERROR(204),
    OPTIONAL_TFLITE_MODULE_INIT_ERROR(205),
    NATIVE_LIBRARY_LOAD_ERROR(206),
    OPTIONAL_MODULE_CREATE_ERROR(207),
    CAMERAX_SOURCE_ERROR(301),
    CAMERA1_SOURCE_CANT_START_ERROR(HttpStatus.SC_MOVED_TEMPORARILY),
    CAMERA1_SOURCE_NO_SUITABLE_SIZE_ERROR(HttpStatus.SC_SEE_OTHER),
    CAMERA1_SOURCE_NO_SUITABLE_FPS_ERROR(HttpStatus.SC_NOT_MODIFIED),
    CAMERA1_SOURCE_NO_BYTE_SOURCE_FOUND_ERROR(HttpStatus.SC_USE_PROXY),
    CODE_SCANNER_UNAVAILABLE(HttpStatus.SC_BAD_REQUEST),
    CODE_SCANNER_CANCELLED(HttpStatus.SC_UNAUTHORIZED),
    CODE_SCANNER_CAMERA_PERMISSION_NOT_GRANTED(HttpStatus.SC_PAYMENT_REQUIRED),
    CODE_SCANNER_APP_NAME_UNAVAILABLE(HttpStatus.SC_FORBIDDEN),
    CODE_SCANNER_TASK_IN_PROGRESS(HttpStatus.SC_NOT_FOUND),
    CODE_SCANNER_PIPELINE_INITIALIZATION_ERROR(HttpStatus.SC_METHOD_NOT_ALLOWED),
    CODE_SCANNER_PIPELINE_INFERENCE_ERROR(HttpStatus.SC_NOT_ACCEPTABLE),
    CODE_SCANNER_GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(HttpStatus.SC_PROXY_AUTHENTICATION_REQUIRED),
    LOW_LIGHT_AUTO_EXPOSURE_COMPUTATION_FAILURE(500),
    LOW_LIGHT_IMAGE_CAPTURE_PROCESSING_FAILURE(HttpStatus.SC_NOT_IMPLEMENTED),
    PERMISSION_DENIED(600),
    CANCELLED(601),
    GOOGLE_PLAY_SERVICES_VERSION_TOO_OLD(602),
    LOW_MEMORY(603),
    UNKNOWN_ERROR(9999);

    private final int a;

    n3m(int i) {
        this.a = i;
    }

    @Override // defpackage.x5l
    public final int zza() {
        return this.a;
    }
}
