package defpackage;

import java.util.ArrayList;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.Set;

/* JADX INFO: loaded from: classes3.dex */
public final /* synthetic */ class o14 implements cf7 {
    public final /* synthetic */ int a = 0;
    public final /* synthetic */ String b;
    public final /* synthetic */ int c;
    public final /* synthetic */ long d;
    public final /* synthetic */ long e;
    public final /* synthetic */ wja f;
    public final /* synthetic */ Collection g;
    public final /* synthetic */ Object h;

    public /* synthetic */ o14(String str, long j, long j2, List list, int i, g24 g24Var, wja wjaVar) {
        this.b = str;
        this.d = j;
        this.e = j2;
        this.g = list;
        this.c = i;
        this.h = g24Var;
        this.f = wjaVar;
    }

    @Override // defpackage.cf7
    public final Object invoke(Object obj) throws Exception {
        int i = this.a;
        String str = "status";
        String str2 = "delivery_status";
        wja wjaVar = this.f;
        Object obj2 = this.h;
        long j = this.e;
        long j2 = this.d;
        int i2 = this.c;
        Collection collection = this.g;
        String str3 = this.b;
        switch (i) {
            case 0:
                List list = (List) collection;
                g24 g24Var = (g24) obj2;
                vxe vxeVarO0 = ((qxe) obj).O0(str3);
                try {
                    vxeVarO0.c(1, j2);
                    vxeVarO0.c(2, j);
                    int i3 = 3;
                    for (Iterator it = list.iterator(); it.hasNext(); it = it) {
                        vxeVarO0.c(i3, ((Number) it.next()).longValue());
                        i3++;
                    }
                    g24Var.a().getClass();
                    vxeVarO0.c(i2 + 3, wjaVar.a);
                    int iE = qyj.E(vxeVarO0, "id");
                    int iE2 = qyj.E(vxeVarO0, "server_id");
                    int iE3 = qyj.E(vxeVarO0, "time");
                    int iE4 = qyj.E(vxeVarO0, "update_time");
                    int iE5 = qyj.E(vxeVarO0, "sender");
                    int iE6 = qyj.E(vxeVarO0, "cid");
                    int iE7 = qyj.E(vxeVarO0, "text");
                    int iE8 = qyj.E(vxeVarO0, "delivery_status");
                    int iE9 = qyj.E(vxeVarO0, "status");
                    int iE10 = qyj.E(vxeVarO0, "status_in_process");
                    int iE11 = qyj.E(vxeVarO0, "time_local");
                    int iE12 = qyj.E(vxeVarO0, "error");
                    int iE13 = qyj.E(vxeVarO0, "localized_error");
                    int iE14 = qyj.E(vxeVarO0, "attaches");
                    int iE15 = qyj.E(vxeVarO0, "media_type");
                    int iE16 = qyj.E(vxeVarO0, "message_type");
                    int iE17 = qyj.E(vxeVarO0, "detect_share");
                    int iE18 = qyj.E(vxeVarO0, "msg_link_type");
                    int iE19 = qyj.E(vxeVarO0, "msg_link_id");
                    int iE20 = qyj.E(vxeVarO0, "inserted_from_msg_link");
                    int iE21 = qyj.E(vxeVarO0, "msg_link_out_chat_id");
                    int iE22 = qyj.E(vxeVarO0, "msg_link_out_post_id");
                    int iE23 = qyj.E(vxeVarO0, "msg_link_out_msg_id");
                    int iE24 = qyj.E(vxeVarO0, "options");
                    int iE25 = qyj.E(vxeVarO0, "elements");
                    int iE26 = qyj.E(vxeVarO0, "reactions");
                    int iE27 = qyj.E(vxeVarO0, "reactions_update_time");
                    int iE28 = qyj.E(vxeVarO0, "parent_chat_server_id");
                    int iE29 = qyj.E(vxeVarO0, "parent_message_server_id");
                    ArrayList arrayList = new ArrayList();
                    while (vxeVarO0.M0()) {
                        long j3 = vxeVarO0.getLong(iE);
                        long j4 = vxeVarO0.getLong(iE2);
                        long j5 = vxeVarO0.getLong(iE3);
                        long j6 = vxeVarO0.getLong(iE4);
                        long j7 = vxeVarO0.getLong(iE5);
                        long j8 = vxeVarO0.getLong(iE6);
                        String strB0 = vxeVarO0.isNull(iE7) ? null : vxeVarO0.B0(iE7);
                        int i4 = (int) vxeVarO0.getLong(iE8);
                        g24Var.a().getClass();
                        xfa xfaVarB = dwa.b(i4);
                        int i5 = (int) vxeVarO0.getLong(iE9);
                        g24Var.a().getClass();
                        wja wjaVarD = dwa.d(i5);
                        boolean z = ((int) vxeVarO0.getLong(iE10)) != 0;
                        long j9 = vxeVarO0.getLong(iE11);
                        String strB1 = vxeVarO0.isNull(iE12) ? null : vxeVarO0.B0(iE12);
                        String strB2 = vxeVarO0.isNull(iE13) ? null : vxeVarO0.B0(iE13);
                        byte[] blob = vxeVarO0.isNull(iE14) ? null : vxeVarO0.getBlob(iE14);
                        g24Var.a().getClass();
                        c46 c46VarA = dwa.a(blob);
                        int i6 = iE15;
                        int i7 = iE3;
                        int i8 = (int) vxeVarO0.getLong(i6);
                        int i9 = iE16;
                        int i10 = (int) vxeVarO0.getLong(i9);
                        g24Var.a().getClass();
                        int iE30 = dwa.e(i10);
                        iE16 = i9;
                        int i11 = iE17;
                        boolean z2 = ((int) vxeVarO0.getLong(i11)) != 0;
                        int i12 = iE9;
                        int i13 = iE7;
                        int i14 = iE18;
                        int i15 = (int) vxeVarO0.getLong(i14);
                        int i16 = iE19;
                        long j10 = vxeVarO0.getLong(i16);
                        int i17 = iE20;
                        boolean z3 = ((int) vxeVarO0.getLong(i17)) != 0;
                        int i18 = iE21;
                        long j11 = vxeVarO0.getLong(i18);
                        int i19 = iE22;
                        long j12 = vxeVarO0.getLong(i19);
                        int i20 = iE23;
                        long j13 = vxeVarO0.getLong(i20);
                        iE23 = i20;
                        int i21 = iE24;
                        int i22 = (int) vxeVarO0.getLong(i21);
                        int i23 = iE25;
                        byte[] blob2 = vxeVarO0.getBlob(i23);
                        g24Var.a().getClass();
                        List listC = dwa.c(blob2);
                        int i24 = iE26;
                        kja kjaVarF = g24Var.a().f(vxeVarO0.isNull(i24) ? null : vxeVarO0.getBlob(i24));
                        int i25 = iE27;
                        long j14 = vxeVarO0.getLong(i25);
                        int i26 = iE28;
                        iE27 = i25;
                        int i27 = iE29;
                        arrayList.add(new uy3(j3, new q24(vxeVarO0.getLong(i26), vxeVarO0.getLong(i27)), j4, j5, j6, j7, j8, strB0, xfaVarB, wjaVarD, z, j9, strB1, strB2, c46VarA, i8, iE30, z2, i15, j10, z3, j11, j12, j13, i22, listC, kjaVarF, j14));
                        iE3 = i7;
                        iE9 = i12;
                        iE17 = i11;
                        iE18 = i14;
                        iE7 = i13;
                        iE20 = i17;
                        iE21 = i18;
                        iE22 = i19;
                        iE24 = i21;
                        iE19 = i16;
                        iE25 = i23;
                        iE28 = i26;
                        iE = iE;
                        iE2 = iE2;
                        iE15 = i6;
                        iE26 = i24;
                        iE29 = i27;
                        break;
                    }
                    return arrayList;
                } finally {
                    vxeVarO0.close();
                }
            default:
                Set set = (Set) collection;
                toa toaVar = (toa) obj2;
                vxe vxeVarO1 = ((qxe) obj).O0(str3);
                try {
                    Iterator it2 = set.iterator();
                    int i28 = 1;
                    while (it2.hasNext()) {
                        vxeVarO1.c(i28, ((Number) it2.next()).intValue());
                        i28++;
                        str = str;
                        str2 = str2;
                    }
                    String str4 = str;
                    String str5 = str2;
                    vxeVarO1.c(i2 + 1, j2);
                    vxeVarO1.c(i2 + 2, j);
                    toaVar.e().getClass();
                    vxeVarO1.c(i2 + 3, wjaVar.a);
                    vxeVarO1.c(i2 + 4, 100L);
                    int iE31 = qyj.E(vxeVarO1, "id");
                    int iE32 = qyj.E(vxeVarO1, "server_id");
                    int iE33 = qyj.E(vxeVarO1, "time");
                    int iE34 = qyj.E(vxeVarO1, "update_time");
                    int iE35 = qyj.E(vxeVarO1, "sender");
                    int iE36 = qyj.E(vxeVarO1, "cid");
                    int iE37 = qyj.E(vxeVarO1, "text");
                    int iE38 = qyj.E(vxeVarO1, str5);
                    int iE39 = qyj.E(vxeVarO1, str4);
                    int iE40 = qyj.E(vxeVarO1, "status_in_process");
                    int iE41 = qyj.E(vxeVarO1, "time_local");
                    int iE42 = qyj.E(vxeVarO1, "error");
                    int iE43 = qyj.E(vxeVarO1, "localized_error");
                    int iE44 = qyj.E(vxeVarO1, "attaches");
                    int iE45 = qyj.E(vxeVarO1, "media_type");
                    int iE46 = qyj.E(vxeVarO1, "detect_share");
                    int iE47 = qyj.E(vxeVarO1, "msg_link_type");
                    int iE48 = qyj.E(vxeVarO1, "msg_link_id");
                    int iE49 = qyj.E(vxeVarO1, "inserted_from_msg_link");
                    int iE50 = qyj.E(vxeVarO1, "msg_link_chat_id");
                    int iE51 = qyj.E(vxeVarO1, "msg_link_chat_name");
                    int iE52 = qyj.E(vxeVarO1, "msg_link_chat_link");
                    int iE53 = qyj.E(vxeVarO1, "msg_link_chat_icon_url");
                    int iE54 = qyj.E(vxeVarO1, "msg_link_chat_access_type");
                    int iE55 = qyj.E(vxeVarO1, "msg_link_out_chat_id");
                    int iE56 = qyj.E(vxeVarO1, "msg_link_out_msg_id");
                    int iE57 = qyj.E(vxeVarO1, "type");
                    int iE58 = qyj.E(vxeVarO1, "chat_id");
                    int iE59 = qyj.E(vxeVarO1, "channel_views");
                    int iE60 = qyj.E(vxeVarO1, "channel_forwards");
                    int iE61 = qyj.E(vxeVarO1, "view_time");
                    int iE62 = qyj.E(vxeVarO1, "options");
                    int iE63 = qyj.E(vxeVarO1, "live_until");
                    int iE64 = qyj.E(vxeVarO1, "elements");
                    int iE65 = qyj.E(vxeVarO1, "reactions");
                    int iE66 = qyj.E(vxeVarO1, "delayed_attrs_time_to_fire");
                    int iE67 = qyj.E(vxeVarO1, "delayed_attrs_notify_sender");
                    int iE68 = qyj.E(vxeVarO1, "reactions_update_time");
                    ArrayList arrayList2 = new ArrayList();
                    while (vxeVarO1.M0()) {
                        long j15 = vxeVarO1.getLong(iE31);
                        long j16 = vxeVarO1.getLong(iE32);
                        long j17 = vxeVarO1.getLong(iE33);
                        long j18 = vxeVarO1.getLong(iE34);
                        long j19 = vxeVarO1.getLong(iE35);
                        long j20 = vxeVarO1.getLong(iE36);
                        String strB3 = vxeVarO1.isNull(iE37) ? null : vxeVarO1.B0(iE37);
                        int i29 = (int) vxeVarO1.getLong(iE38);
                        toaVar.e().getClass();
                        xfa xfaVarB2 = dwa.b(i29);
                        int i30 = (int) vxeVarO1.getLong(iE39);
                        toaVar.e().getClass();
                        wja wjaVarD2 = dwa.d(i30);
                        boolean z4 = ((int) vxeVarO1.getLong(iE40)) != 0;
                        long j21 = vxeVarO1.getLong(iE41);
                        String strB4 = vxeVarO1.isNull(iE42) ? null : vxeVarO1.B0(iE42);
                        String strB5 = vxeVarO1.isNull(iE43) ? null : vxeVarO1.B0(iE43);
                        byte[] blob3 = vxeVarO1.isNull(iE44) ? null : vxeVarO1.getBlob(iE44);
                        toaVar.e().getClass();
                        c46 c46VarA2 = dwa.a(blob3);
                        int i31 = iE45;
                        int i32 = iE33;
                        int i33 = (int) vxeVarO1.getLong(i31);
                        int i34 = iE46;
                        boolean z5 = ((int) vxeVarO1.getLong(i34)) != 0;
                        int i35 = iE47;
                        int i36 = (int) vxeVarO1.getLong(i35);
                        int i37 = iE48;
                        long j22 = vxeVarO1.getLong(i37);
                        int i38 = iE49;
                        boolean z6 = ((int) vxeVarO1.getLong(i38)) != 0;
                        int i39 = iE50;
                        long j23 = vxeVarO1.getLong(i39);
                        int i40 = iE51;
                        String strB6 = vxeVarO1.isNull(i40) ? null : vxeVarO1.B0(i40);
                        int i41 = iE52;
                        String strB7 = vxeVarO1.isNull(i41) ? null : vxeVarO1.B0(i41);
                        iE52 = i41;
                        int i42 = iE53;
                        String strB8 = vxeVarO1.isNull(i42) ? null : vxeVarO1.B0(i42);
                        iE53 = i42;
                        int i43 = iE54;
                        Integer numValueOf = vxeVarO1.isNull(i43) ? null : Integer.valueOf((int) vxeVarO1.getLong(i43));
                        toaVar.d().getClass();
                        int iA = vo3.a(numValueOf);
                        int i44 = iE55;
                        long j24 = vxeVarO1.getLong(i44);
                        int i45 = iE56;
                        long j25 = vxeVarO1.getLong(i45);
                        int i46 = iE57;
                        int i47 = (int) vxeVarO1.getLong(i46);
                        toaVar.e().getClass();
                        int iE69 = dwa.e(i47);
                        int i48 = iE58;
                        long j26 = vxeVarO1.getLong(i48);
                        int i49 = iE59;
                        int i50 = (int) vxeVarO1.getLong(i49);
                        int i51 = iE60;
                        int i52 = iE34;
                        int i53 = (int) vxeVarO1.getLong(i51);
                        int i54 = iE61;
                        long j27 = vxeVarO1.getLong(i54);
                        int i55 = iE62;
                        int i56 = (int) vxeVarO1.getLong(i55);
                        int i57 = iE63;
                        long j28 = vxeVarO1.getLong(i57);
                        iE62 = i55;
                        int i58 = iE64;
                        byte[] blob4 = vxeVarO1.getBlob(i58);
                        toaVar.e().getClass();
                        List listC2 = dwa.c(blob4);
                        iE64 = i58;
                        iE65 = iE65;
                        kja kjaVarF2 = toaVar.e().f(vxeVarO1.isNull(iE65) ? null : vxeVarO1.getBlob(iE65));
                        int i59 = iE66;
                        Long lValueOf = vxeVarO1.isNull(i59) ? null : Long.valueOf(vxeVarO1.getLong(i59));
                        int i60 = iE67;
                        Integer numValueOf2 = vxeVarO1.isNull(i60) ? null : Integer.valueOf((int) vxeVarO1.getLong(i60));
                        Boolean boolValueOf = numValueOf2 != null ? Boolean.valueOf(numValueOf2.intValue() != 0) : null;
                        int i61 = iE68;
                        arrayList2.add(new gga(j15, j16, j17, j18, j19, j20, strB3, xfaVarB2, wjaVarD2, z4, j21, strB4, strB5, c46VarA2, i33, z5, i36, j22, z6, j23, strB6, strB7, strB8, iA, j24, j25, iE69, j26, i50, i53, j27, i56, j28, listC2, kjaVarF2, lValueOf, boolValueOf, vxeVarO1.getLong(i61)));
                        iE67 = i60;
                        iE68 = i61;
                        iE34 = i52;
                        iE60 = i51;
                        iE61 = i54;
                        iE63 = i57;
                        iE32 = iE32;
                        iE33 = i32;
                        iE45 = i31;
                        iE66 = i59;
                        iE46 = i34;
                        iE47 = i35;
                        iE48 = i37;
                        iE49 = i38;
                        iE50 = i39;
                        iE51 = i40;
                        iE54 = i43;
                        iE55 = i44;
                        iE56 = i45;
                        iE57 = i46;
                        iE58 = i48;
                        iE31 = iE31;
                        iE59 = i49;
                        break;
                    }
                    return arrayList2;
                } finally {
                    vxeVarO1.close();
                }
        }
    }

    public /* synthetic */ o14(String str, Set set, int i, long j, long j2, toa toaVar, wja wjaVar) {
        this.b = str;
        this.g = set;
        this.c = i;
        this.d = j;
        this.e = j2;
        this.h = toaVar;
        this.f = wjaVar;
    }
}
