package defpackage;

/* JADX INFO: loaded from: classes.dex */
public final class ozc {
    public final p3d A;
    public final sib B;
    public final gue C;
    public final w8g D;
    public final apa E;
    public final ny8 F;
    public final ny8 G;
    public final ny8 H;
    public final ny8 I;
    public final ny8 J;
    public final ny8 K;
    public final t51 L;
    public final ite a;
    public final xhh b;
    public final ny8 c;
    public final ny8 d;
    public final ny8 e;
    public final ny8 f;
    public final ny8 g;
    public final ny8 h;
    public final ny8 i;
    public final ny8 j;
    public final ny8 k;
    public final ny8 l;
    public final ny8 m;
    public final ny8 n;
    public final w7b o;
    public final ny8 p;
    public final ny8 q;
    public final ny8 r;
    public final ny8 s;
    public final ny8 t;
    public final ny8 u;
    public final ny8 v;
    public final ny8 w;
    public final ny8 x;
    public final ny8 y;
    public final ny8 z;

    public ozc(ite iteVar, xhh xhhVar, ny8 ny8Var, ny8 ny8Var2, ny8 ny8Var3, ny8 ny8Var4, ny8 ny8Var5, ny8 ny8Var6, ny8 ny8Var7, ny8 ny8Var8, ny8 ny8Var9, ny8 ny8Var10, ny8 ny8Var11, ny8 ny8Var12, w7b w7bVar, ny8 ny8Var13, ny8 ny8Var14, ny8 ny8Var15, ny8 ny8Var16, ny8 ny8Var17, ny8 ny8Var18, ny8 ny8Var19, ny8 ny8Var20, ny8 ny8Var21, ny8 ny8Var22, ny8 ny8Var23, p3d p3dVar, sib sibVar, gue gueVar, w8g w8gVar, apa apaVar, ny8 ny8Var24, ny8 ny8Var25, ny8 ny8Var26, ny8 ny8Var27, ny8 ny8Var28, ny8 ny8Var29, t51 t51Var) {
        this.a = iteVar;
        this.b = xhhVar;
        this.c = ny8Var;
        this.d = ny8Var2;
        this.e = ny8Var3;
        this.f = ny8Var4;
        this.g = ny8Var5;
        this.h = ny8Var6;
        this.i = ny8Var7;
        this.j = ny8Var8;
        this.k = ny8Var9;
        this.l = ny8Var10;
        this.m = ny8Var11;
        this.n = ny8Var12;
        this.o = w7bVar;
        this.p = ny8Var13;
        this.q = ny8Var14;
        this.r = ny8Var15;
        this.s = ny8Var16;
        this.t = ny8Var17;
        this.u = ny8Var18;
        this.v = ny8Var19;
        this.w = ny8Var20;
        this.x = ny8Var21;
        this.y = ny8Var22;
        this.z = ny8Var23;
        this.A = p3dVar;
        this.B = sibVar;
        this.C = gueVar;
        this.D = w8gVar;
        this.E = apaVar;
        this.F = ny8Var24;
        this.G = ny8Var25;
        this.H = ny8Var26;
        this.I = ny8Var27;
        this.J = ny8Var28;
        this.K = ny8Var29;
        this.L = t51Var;
    }
}
