package defpackage;

/* JADX INFO: loaded from: classes2.dex */
public final class p3l implements zpb {
    public static final p3l a = new p3l();
    public static final jp6 b = new jp6("systemInfo", p.h(ewi.f(aok.class, new dnk(1))));
    public static final jp6 c = new jp6("eventName", p.h(ewi.f(aok.class, new dnk(2))));
    public static final jp6 d = new jp6("isThickClient", p.h(ewi.f(aok.class, new dnk(37))));
    public static final jp6 e = new jp6("clientType", p.h(ewi.f(aok.class, new dnk(61))));
    public static final jp6 f = new jp6("modelDownloadLogEvent", p.h(ewi.f(aok.class, new dnk(3))));
    public static final jp6 g = new jp6("customModelLoadLogEvent", p.h(ewi.f(aok.class, new dnk(20))));
    public static final jp6 h = new jp6("customModelInferenceLogEvent", p.h(ewi.f(aok.class, new dnk(4))));
    public static final jp6 i = new jp6("customModelCreateLogEvent", p.h(ewi.f(aok.class, new dnk(29))));
    public static final jp6 j = new jp6("onDeviceFaceDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(5))));
    public static final jp6 k = new jp6("onDeviceFaceLoadLogEvent", p.h(ewi.f(aok.class, new dnk(59))));
    public static final jp6 l = new jp6("onDeviceTextDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(6))));
    public static final jp6 m = new jp6("onDeviceTextDetectionLoadLogEvent", p.h(ewi.f(aok.class, new dnk(79))));
    public static final jp6 n = new jp6("onDeviceBarcodeDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(7))));
    public static final jp6 o = new jp6("onDeviceBarcodeLoadLogEvent", p.h(ewi.f(aok.class, new dnk(58))));
    public static final jp6 p = new jp6("onDeviceImageLabelCreateLogEvent", p.h(ewi.f(aok.class, new dnk(48))));
    public static final jp6 q = new jp6("onDeviceImageLabelLoadLogEvent", p.h(ewi.f(aok.class, new dnk(49))));
    public static final jp6 r = new jp6("onDeviceImageLabelDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(18))));
    public static final jp6 s = new jp6("onDeviceObjectCreateLogEvent", p.h(ewi.f(aok.class, new dnk(26))));
    public static final jp6 t = new jp6("onDeviceObjectLoadLogEvent", p.h(ewi.f(aok.class, new dnk(27))));
    public static final jp6 u = new jp6("onDeviceObjectInferenceLogEvent", p.h(ewi.f(aok.class, new dnk(28))));
    public static final jp6 v = new jp6("onDevicePoseDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(44))));
    public static final jp6 w = new jp6("onDeviceSegmentationLogEvent", p.h(ewi.f(aok.class, new dnk(45))));
    public static final jp6 x = new jp6("onDeviceSmartReplyLogEvent", p.h(ewi.f(aok.class, new dnk(19))));
    public static final jp6 y = new jp6("onDeviceLanguageIdentificationLogEvent", p.h(ewi.f(aok.class, new dnk(21))));
    public static final jp6 z = new jp6("onDeviceTranslationLogEvent", p.h(ewi.f(aok.class, new dnk(22))));
    public static final jp6 A = new jp6("cloudFaceDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(8))));
    public static final jp6 B = new jp6("cloudCropHintDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(9))));
    public static final jp6 C = new jp6("cloudDocumentTextDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(10))));
    public static final jp6 D = new jp6("cloudImagePropertiesDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(11))));
    public static final jp6 E = new jp6("cloudImageLabelDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(12))));
    public static final jp6 F = new jp6("cloudLandmarkDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(13))));
    public static final jp6 G = new jp6("cloudLogoDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(14))));
    public static final jp6 H = new jp6("cloudSafeSearchDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(15))));
    public static final jp6 I = new jp6("cloudTextDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(16))));
    public static final jp6 J = new jp6("cloudWebSearchDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(17))));
    public static final jp6 K = new jp6("automlImageLabelingCreateLogEvent", p.h(ewi.f(aok.class, new dnk(23))));
    public static final jp6 L = new jp6("automlImageLabelingLoadLogEvent", p.h(ewi.f(aok.class, new dnk(24))));
    public static final jp6 M = new jp6("automlImageLabelingInferenceLogEvent", p.h(ewi.f(aok.class, new dnk(25))));
    public static final jp6 N = new jp6("isModelDownloadedLogEvent", p.h(ewi.f(aok.class, new dnk(39))));
    public static final jp6 O = new jp6("deleteModelLogEvent", p.h(ewi.f(aok.class, new dnk(40))));
    public static final jp6 P = new jp6("aggregatedAutomlImageLabelingInferenceLogEvent", p.h(ewi.f(aok.class, new dnk(30))));
    public static final jp6 Q = new jp6("aggregatedCustomModelInferenceLogEvent", p.h(ewi.f(aok.class, new dnk(31))));
    public static final jp6 R = new jp6("aggregatedOnDeviceFaceDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(32))));
    public static final jp6 S = new jp6("aggregatedOnDeviceBarcodeDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(33))));
    public static final jp6 T = new jp6("aggregatedOnDeviceImageLabelDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(34))));
    public static final jp6 U = new jp6("aggregatedOnDeviceObjectInferenceLogEvent", p.h(ewi.f(aok.class, new dnk(35))));
    public static final jp6 V = new jp6("aggregatedOnDeviceTextDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(36))));
    public static final jp6 W = new jp6("aggregatedOnDevicePoseDetectionLogEvent", p.h(ewi.f(aok.class, new dnk(46))));
    public static final jp6 X = new jp6("aggregatedOnDeviceSegmentationLogEvent", p.h(ewi.f(aok.class, new dnk(47))));
    public static final jp6 Y = new jp6("pipelineAccelerationInferenceEvents", p.h(ewi.f(aok.class, new dnk(69))));
    public static final jp6 Z = new jp6("remoteConfigLogEvent", p.h(ewi.f(aok.class, new dnk(42))));
    public static final jp6 a0 = new jp6("inputImageConstructionLogEvent", p.h(ewi.f(aok.class, new dnk(50))));
    public static final jp6 b0 = new jp6("leakedHandleEvent", p.h(ewi.f(aok.class, new dnk(51))));
    public static final jp6 c0 = new jp6("cameraSourceLogEvent", p.h(ewi.f(aok.class, new dnk(52))));
    public static final jp6 d0 = new jp6("imageLabelOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(53))));
    public static final jp6 e0 = new jp6("languageIdentificationOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(54))));
    public static final jp6 f0 = new jp6("faceDetectionOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(60))));
    public static final jp6 g0 = new jp6("documentDetectionOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(85))));
    public static final jp6 h0 = new jp6("documentCroppingOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(86))));
    public static final jp6 i0 = new jp6("documentEnhancementOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(87))));
    public static final jp6 j0 = new jp6("nlClassifierOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(55))));
    public static final jp6 k0 = new jp6("nlClassifierClientLibraryLogEvent", p.h(ewi.f(aok.class, new dnk(56))));
    public static final jp6 l0 = new jp6("accelerationAllowlistLogEvent", p.h(ewi.f(aok.class, new dnk(57))));
    public static final jp6 m0 = new jp6("toxicityDetectionCreateEvent", p.h(ewi.f(aok.class, new dnk(62))));
    public static final jp6 n0 = new jp6("toxicityDetectionLoadEvent", p.h(ewi.f(aok.class, new dnk(63))));
    public static final jp6 o0 = new jp6("toxicityDetectionInferenceEvent", p.h(ewi.f(aok.class, new dnk(64))));
    public static final jp6 p0 = new jp6("barcodeDetectionOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(65))));
    public static final jp6 q0 = new jp6("customImageLabelOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(66))));
    public static final jp6 r0 = new jp6("codeScannerScanApiEvent", p.h(ewi.f(aok.class, new dnk(67))));
    public static final jp6 s0 = new jp6("codeScannerOptionalModuleEvent", p.h(ewi.f(aok.class, new dnk(68))));
    public static final jp6 t0 = new jp6("onDeviceExplicitContentCreateLogEvent", p.h(ewi.f(aok.class, new dnk(70))));
    public static final jp6 u0 = new jp6("onDeviceExplicitContentLoadLogEvent", p.h(ewi.f(aok.class, new dnk(71))));
    public static final jp6 v0 = new jp6("onDeviceExplicitContentInferenceLogEvent", p.h(ewi.f(aok.class, new dnk(72))));
    public static final jp6 w0 = new jp6("aggregatedOnDeviceExplicitContentLogEvent", p.h(ewi.f(aok.class, new dnk(73))));
    public static final jp6 x0 = new jp6("onDeviceFaceMeshCreateLogEvent", p.h(ewi.f(aok.class, new dnk(74))));
    public static final jp6 y0 = new jp6("onDeviceFaceMeshLoadLogEvent", p.h(ewi.f(aok.class, new dnk(75))));
    public static final jp6 z0 = new jp6("onDeviceFaceMeshLogEvent", p.h(ewi.f(aok.class, new dnk(76))));
    public static final jp6 A0 = new jp6("aggregatedOnDeviceFaceMeshLogEvent", p.h(ewi.f(aok.class, new dnk(77))));
    public static final jp6 B0 = new jp6("smartReplyOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(78))));
    public static final jp6 C0 = new jp6("textDetectionOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(80))));
    public static final jp6 D0 = new jp6("onDeviceImageQualityAnalysisCreateLogEvent", p.h(ewi.f(aok.class, new dnk(81))));
    public static final jp6 E0 = new jp6("onDeviceImageQualityAnalysisLoadLogEvent", p.h(ewi.f(aok.class, new dnk(82))));
    public static final jp6 F0 = new jp6("onDeviceImageQualityAnalysisLogEvent", p.h(ewi.f(aok.class, new dnk(83))));
    public static final jp6 G0 = new jp6("aggregatedOnDeviceImageQualityAnalysisLogEvent", p.h(ewi.f(aok.class, new dnk(84))));
    public static final jp6 H0 = new jp6("imageQualityAnalysisOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(88))));
    public static final jp6 I0 = new jp6("imageCaptioningOptionalModuleLogEvent", p.h(ewi.f(aok.class, new dnk(89))));
    public static final jp6 J0 = new jp6("onDeviceImageCaptioningCreateLogEvent", p.h(ewi.f(aok.class, new dnk(90))));
    public static final jp6 K0 = new jp6("onDeviceImageCaptioningLoadLogEvent", p.h(ewi.f(aok.class, new dnk(91))));
    public static final jp6 L0 = new jp6("onDeviceImageCaptioningInferenceLogEvent", p.h(ewi.f(aok.class, new dnk(92))));
    public static final jp6 M0 = new jp6("aggregatedOnDeviceImageCaptioningInferenceLogEvent", p.h(ewi.f(aok.class, new dnk(93))));

    @Override // defpackage.v76
    public final void a(Object obj, Object obj2) {
        fil filVar = (fil) obj;
        aqb aqbVar = (aqb) obj2;
        aqbVar.a(b, filVar.a);
        aqbVar.a(c, filVar.b);
        aqbVar.a(d, null);
        aqbVar.a(e, null);
        aqbVar.a(f, null);
        aqbVar.a(g, null);
        aqbVar.a(h, null);
        aqbVar.a(i, null);
        aqbVar.a(j, null);
        aqbVar.a(k, null);
        aqbVar.a(l, null);
        aqbVar.a(m, null);
        aqbVar.a(n, null);
        aqbVar.a(o, null);
        aqbVar.a(p, null);
        aqbVar.a(q, null);
        aqbVar.a(r, null);
        aqbVar.a(s, null);
        aqbVar.a(t, null);
        aqbVar.a(u, null);
        aqbVar.a(v, null);
        aqbVar.a(w, null);
        aqbVar.a(x, null);
        aqbVar.a(y, null);
        aqbVar.a(z, null);
        aqbVar.a(A, null);
        aqbVar.a(B, null);
        aqbVar.a(C, null);
        aqbVar.a(D, null);
        aqbVar.a(E, null);
        aqbVar.a(F, null);
        aqbVar.a(G, null);
        aqbVar.a(H, null);
        aqbVar.a(I, null);
        aqbVar.a(J, null);
        aqbVar.a(K, null);
        aqbVar.a(L, null);
        aqbVar.a(M, null);
        aqbVar.a(N, null);
        aqbVar.a(O, null);
        aqbVar.a(P, null);
        aqbVar.a(Q, null);
        aqbVar.a(R, null);
        aqbVar.a(S, null);
        aqbVar.a(T, null);
        aqbVar.a(U, null);
        aqbVar.a(V, null);
        aqbVar.a(W, null);
        aqbVar.a(X, null);
        aqbVar.a(Y, null);
        aqbVar.a(Z, null);
        aqbVar.a(a0, filVar.c);
        aqbVar.a(b0, null);
        aqbVar.a(c0, null);
        aqbVar.a(d0, null);
        aqbVar.a(e0, null);
        aqbVar.a(f0, null);
        aqbVar.a(g0, null);
        aqbVar.a(h0, null);
        aqbVar.a(i0, null);
        aqbVar.a(j0, null);
        aqbVar.a(k0, null);
        aqbVar.a(l0, null);
        aqbVar.a(m0, null);
        aqbVar.a(n0, null);
        aqbVar.a(o0, null);
        aqbVar.a(p0, null);
        aqbVar.a(q0, null);
        aqbVar.a(r0, null);
        aqbVar.a(s0, null);
        aqbVar.a(t0, null);
        aqbVar.a(u0, null);
        aqbVar.a(v0, null);
        aqbVar.a(w0, null);
        aqbVar.a(x0, null);
        aqbVar.a(y0, null);
        aqbVar.a(z0, null);
        aqbVar.a(A0, null);
        aqbVar.a(B0, null);
        aqbVar.a(C0, null);
        aqbVar.a(D0, null);
        aqbVar.a(E0, null);
        aqbVar.a(F0, null);
        aqbVar.a(G0, null);
        aqbVar.a(H0, null);
        aqbVar.a(I0, null);
        aqbVar.a(J0, null);
        aqbVar.a(K0, null);
        aqbVar.a(L0, null);
        aqbVar.a(M0, null);
    }
}
