package defpackage;

import android.content.Context;
import android.net.ConnectivityManager;
import java.util.concurrent.ExecutorService;
import java.util.concurrent.Executors;
import org.webrtc.EglBase;
import ru.ok.android.externcalls.analytics.CallAnalyticsSender;
import ru.ok.android.externcalls.sdk.api.CallApiServiceImpl;
import ru.ok.android.externcalls.sdk.factory.internal.CidLogger;
import ru.ok.android.externcalls.sdk.record.internal.RecordManagerImpl;

/* JADX INFO: loaded from: classes3.dex */
public final class pr1 {
    public final xt1 a;
    public final du1 b;
    public final CidLogger c;
    public final z3e d;
    public final esh e;
    public final ode f;
    public final xq1 g;
    public final fik h;
    public final ru1 i;
    public final cmf j;
    public final vn7 k;
    public final ou7 l;
    public final cw5 m;
    public final due n;
    public final i32 o;
    public final EglBase p;
    public final ExecutorService q;
    public final ExecutorService r;
    public final ug5 s;
    public final zzf t;
    public final lb9 u;
    public final fwg v;
    public final zq1 w;
    public final k5g x;
    public final ew6 y;
    public final ifh z;

    public pr1(Context context, xt1 xt1Var, boolean z, boolean z2, du1 du1Var, qs4 qs4Var, CidLogger cidLogger, z3e z3eVar, opb opbVar, nue nueVar, wl wlVar, esh eshVar, CallAnalyticsSender callAnalyticsSender, xdd xddVar, a4f a4fVar, bj1 bj1Var, CallApiServiceImpl callApiServiceImpl, px8 px8Var, RecordManagerImpl recordManagerImpl, xoc xocVar, long j) {
        context.getClass();
        xt1Var.getClass();
        z3eVar.getClass();
        opbVar.getClass();
        wlVar.getClass();
        eshVar.getClass();
        callAnalyticsSender.getClass();
        recordManagerImpl.getClass();
        xocVar.getClass();
        this.a = xt1Var;
        this.b = du1Var;
        this.c = cidLogger;
        this.d = z3eVar;
        this.e = eshVar;
        this.f = recordManagerImpl;
        xq1 xq1Var = new xq1();
        this.g = xq1Var;
        fik fikVar = new fik(xq1Var);
        this.h = fikVar;
        ru1 ru1Var = new ru1(du1Var, xq1Var, fikVar, cidLogger);
        this.i = ru1Var;
        cmf cmfVar = new cmf(cidLogger);
        this.j = cmfVar;
        this.k = new vn7(20);
        ou7 ou7Var = new ou7(21);
        this.l = ou7Var;
        b1k b1kVar = new b1k(16, cidLogger);
        this.m = new cw5(ru1Var, xt1Var, cidLogger, xq1Var, eshVar, px8Var, ou7Var);
        nr1 nr1Var = new nr1(this, 3);
        due dueVar = new due();
        dueVar.a = nr1Var;
        this.n = dueVar;
        jb1 jb1Var = new jb1(callAnalyticsSender);
        Object systemService = context.getSystemService("connectivity");
        systemService.getClass();
        i32 i32Var = new i32(context, jb1Var, eshVar, (ConnectivityManager) systemService, cidLogger, dueVar, qs4Var, xt1Var);
        this.o = i32Var;
        EglBase eglBaseCreate = EglBase.create();
        eglBaseCreate.getClass();
        this.p = eglBaseCreate;
        ExecutorService executorServiceNewSingleThreadExecutor = Executors.newSingleThreadExecutor();
        executorServiceNewSingleThreadExecutor.getClass();
        this.q = executorServiceNewSingleThreadExecutor;
        ExecutorService executorServiceNewSingleThreadExecutor2 = Executors.newSingleThreadExecutor();
        executorServiceNewSingleThreadExecutor2.getClass();
        this.r = executorServiceNewSingleThreadExecutor2;
        ug5 ug5Var = new ug5(cidLogger);
        this.s = ug5Var;
        this.t = new zzf(context, executorServiceNewSingleThreadExecutor, eglBaseCreate, cidLogger, xt1Var, ug5Var, i32Var.j, context.getPackageManager().hasSystemFeature("android.hardware.audio.low_latency"), dueVar, ou7Var, b1kVar);
        lb9 lb9Var = new lb9(context, cidLogger);
        this.u = lb9Var;
        mkc mkcVar = new mkc();
        mkcVar.a = false;
        mkcVar.f = context;
        mkcVar.d = xt1Var.g;
        mkcVar.c = opbVar;
        mkcVar.e = lb9Var;
        mkcVar.a = xt1Var.r.a;
        mkcVar.b = cidLogger;
        this.v = new fwg(mkcVar);
        zq1 zq1Var = new zq1(ru1Var, cidLogger, new wf0(4), new iw8(8), new jc1(0, 23, ru1.class, ru1Var, "activeRoomId", "getActiveRoomId()Lru/ok/android/webrtc/sessionroom/SessionRoomId;"), lb9Var, xt1Var);
        this.w = zq1Var;
        this.x = new k5g(cidLogger, du1Var, zq1Var);
        this.y = new ew6(i32Var.j, cmfVar, eshVar, z, z2, new nr1(this, 4), dueVar, new occ(0, ru1Var, ru1.class, "size", "size()I", 0, 25), cidLogger);
        this.z = new ifh(new br1(2));
    }
}
