package defpackage;

/* JADX WARN: Failed to restore enum class, 'enum' modifier and super class removed */
/* JADX WARN: Unknown enum class pattern. Please report as an issue! */
/* JADX INFO: loaded from: classes3.dex */
public final class qdc {
    public static final qdc A;
    public static final qdc A1;
    public static final qdc B;
    public static final /* synthetic */ qdc[] B1;
    public static final qdc C;
    public static final qdc D;
    public static final qdc E;
    public static final qdc F;
    public static final qdc G;
    public static final qdc H;
    public static final qdc I;
    public static final qdc J;
    public static final qdc K;
    public static final qdc X;
    public static final qdc Y;
    public static final qdc Z;
    public static final qdc a;
    public static final qdc b;
    public static final qdc c;
    public static final qdc d;
    public static final qdc e;
    public static final qdc f;
    public static final qdc g;
    public static final qdc h;
    public static final qdc i;
    public static final qdc j;
    public static final qdc k;
    public static final qdc l;
    public static final qdc m;
    public static final qdc n;
    public static final qdc n1;
    public static final qdc o;
    public static final qdc o1;
    public static final qdc p;
    public static final qdc p1;
    public static final qdc q;
    public static final qdc q1;
    public static final qdc r;
    public static final qdc r1;
    public static final qdc s;
    public static final qdc s1;
    public static final qdc t;
    public static final qdc t1;
    public static final qdc u;
    public static final qdc u1;
    public static final qdc v;
    public static final qdc v1;
    public static final qdc w;
    public static final qdc w1;
    public static final qdc x;
    public static final qdc x1;
    public static final qdc y;
    public static final qdc y1;
    public static final qdc z;
    public static final qdc z1;

    static {
        qdc qdcVar = new qdc("INVALID_STATE", 0);
        a = qdcVar;
        qdc qdcVar2 = new qdc("BAD_VALUE", 1);
        b = qdcVar2;
        qdc qdcVar3 = new qdc("PERMISSION_DENIED", 2);
        c = qdcVar3;
        qdc qdcVar4 = new qdc("NOT_SUPPORTED", 3);
        d = qdcVar4;
        qdc qdcVar5 = new qdc("DISCONNECTED", 4);
        e = qdcVar5;
        qdc qdcVar6 = new qdc("AUTHENTICATION_EXPIRED", 5);
        f = qdcVar6;
        qdc qdcVar7 = new qdc("PREMIUM_ACCOUNT_REQUIRED", 6);
        g = qdcVar7;
        qdc qdcVar8 = new qdc("CONCURRENT_STREAM_LIMIT", 7);
        h = qdcVar8;
        qdc qdcVar9 = new qdc("PARENTAL_CONTROL_RESTRICTED", 8);
        i = qdcVar9;
        qdc qdcVar10 = new qdc("NOT_AVAILABLE_IN_REGION", 9);
        j = qdcVar10;
        qdc qdcVar11 = new qdc("SKIP_LIMIT_REACHED", 10);
        k = qdcVar11;
        qdc qdcVar12 = new qdc("SETUP_REQUIRED", 11);
        l = qdcVar12;
        qdc qdcVar13 = new qdc("END_OF_PLAYLIST", 12);
        m = qdcVar13;
        qdc qdcVar14 = new qdc("CONTENT_ALREADY_PLAYING", 13);
        n = qdcVar14;
        qdc qdcVar15 = new qdc("UNSPECIFIED", 14);
        o = qdcVar15;
        qdc qdcVar16 = new qdc("REMOTE_ERROR", 15);
        p = qdcVar16;
        qdc qdcVar17 = new qdc("BEHIND_LIVE_WINDOW", 16);
        q = qdcVar17;
        qdc qdcVar18 = new qdc("TIMEOUT", 17);
        r = qdcVar18;
        qdc qdcVar19 = new qdc("FAILED_RUNTIME_CHECK", 18);
        s = qdcVar19;
        qdc qdcVar20 = new qdc("IO_UNSPECIFIED", 19);
        t = qdcVar20;
        qdc qdcVar21 = new qdc("IO_NETWORK_CONNECTION_FAILED", 20);
        u = qdcVar21;
        qdc qdcVar22 = new qdc("IO_NETWORK_CONNECTION_TIMEOUT", 21);
        v = qdcVar22;
        qdc qdcVar23 = new qdc("IO_INVALID_HTTP_CONTENT_TYPE", 22);
        w = qdcVar23;
        qdc qdcVar24 = new qdc("IO_BAD_HTTP_STATUS", 23);
        x = qdcVar24;
        qdc qdcVar25 = new qdc("IO_FILE_NOT_FOUND", 24);
        y = qdcVar25;
        qdc qdcVar26 = new qdc("IO_NO_PERMISSION", 25);
        z = qdcVar26;
        qdc qdcVar27 = new qdc("IO_CLEARTEXT_NOT_PERMITTED", 26);
        A = qdcVar27;
        qdc qdcVar28 = new qdc("IO_READ_POSITION_OUT_OF_RANGE", 27);
        B = qdcVar28;
        qdc qdcVar29 = new qdc("PARSING_CONTAINER_MALFORMED", 28);
        C = qdcVar29;
        qdc qdcVar30 = new qdc("PARSING_MANIFEST_MALFORMED", 29);
        D = qdcVar30;
        qdc qdcVar31 = new qdc("PARSING_CONTAINER_UNSUPPORTED", 30);
        E = qdcVar31;
        qdc qdcVar32 = new qdc("PARSING_MANIFEST_UNSUPPORTED", 31);
        F = qdcVar32;
        qdc qdcVar33 = new qdc("DECODER_INIT_FAILED", 32);
        G = qdcVar33;
        qdc qdcVar34 = new qdc("DECODER_QUERY_FAILED", 33);
        H = qdcVar34;
        qdc qdcVar35 = new qdc("DECODING_FAILED", 34);
        I = qdcVar35;
        qdc qdcVar36 = new qdc("DECODING_FORMAT_EXCEEDS_CAPABILITIES", 35);
        J = qdcVar36;
        qdc qdcVar37 = new qdc("DECODING_FORMAT_UNSUPPORTED", 36);
        K = qdcVar37;
        qdc qdcVar38 = new qdc("DECODING_RESOURCES_RECLAIMED", 37);
        X = qdcVar38;
        qdc qdcVar39 = new qdc("AUDIO_TRACK_INIT_FAILED", 38);
        Y = qdcVar39;
        qdc qdcVar40 = new qdc("AUDIO_TRACK_WRITE_FAILED", 39);
        Z = qdcVar40;
        qdc qdcVar41 = new qdc("AUDIO_TRACK_OFFLOAD_WRITE_FAILED", 40);
        n1 = qdcVar41;
        qdc qdcVar42 = new qdc("AUDIO_TRACK_OFFLOAD_INIT_FAILED", 41);
        o1 = qdcVar42;
        qdc qdcVar43 = new qdc("DRM_UNSPECIFIED", 42);
        p1 = qdcVar43;
        qdc qdcVar44 = new qdc("DRM_SCHEME_UNSUPPORTED", 43);
        q1 = qdcVar44;
        qdc qdcVar45 = new qdc("DRM_PROVISIONING_FAILED", 44);
        r1 = qdcVar45;
        qdc qdcVar46 = new qdc("DRM_CONTENT_ERROR", 45);
        s1 = qdcVar46;
        qdc qdcVar47 = new qdc("DRM_LICENSE_ACQUISITION_FAILED", 46);
        t1 = qdcVar47;
        qdc qdcVar48 = new qdc("DRM_DISALLOWED_OPERATION", 47);
        u1 = qdcVar48;
        qdc qdcVar49 = new qdc("DRM_SYSTEM_ERROR", 48);
        v1 = qdcVar49;
        qdc qdcVar50 = new qdc("DRM_DEVICE_REVOKED", 49);
        w1 = qdcVar50;
        qdc qdcVar51 = new qdc("DRM_LICENSE_EXPIRED", 50);
        x1 = qdcVar51;
        qdc qdcVar52 = new qdc("VIDEO_FRAME_PROCESSOR_INIT_FAILED", 51);
        y1 = qdcVar52;
        qdc qdcVar53 = new qdc("VIDEO_FRAME_PROCESSING_FAILED", 52);
        z1 = qdcVar53;
        qdc qdcVar54 = new qdc("NO_ERROR", 53);
        A1 = qdcVar54;
        B1 = new qdc[]{qdcVar, qdcVar2, qdcVar3, qdcVar4, qdcVar5, qdcVar6, qdcVar7, qdcVar8, qdcVar9, qdcVar10, qdcVar11, qdcVar12, qdcVar13, qdcVar14, qdcVar15, qdcVar16, qdcVar17, qdcVar18, qdcVar19, qdcVar20, qdcVar21, qdcVar22, qdcVar23, qdcVar24, qdcVar25, qdcVar26, qdcVar27, qdcVar28, qdcVar29, qdcVar30, qdcVar31, qdcVar32, qdcVar33, qdcVar34, qdcVar35, qdcVar36, qdcVar37, qdcVar38, qdcVar39, qdcVar40, qdcVar41, qdcVar42, qdcVar43, qdcVar44, qdcVar45, qdcVar46, qdcVar47, qdcVar48, qdcVar49, qdcVar50, qdcVar51, qdcVar52, qdcVar53, qdcVar54};
    }

    public static qdc valueOf(String str) {
        return (qdc) Enum.valueOf(qdc.class, str);
    }

    public static qdc[] values() {
        return (qdc[]) B1.clone();
    }
}
