package defpackage;

import com.vk.push.core.base.AidlException;

/* JADX INFO: loaded from: classes4.dex */
public final class val implements zpb {
    public static final jp6 y1;
    public static final val a = new val();
    public static final jp6 b = new jp6("systemInfo", p.h(ewi.g(xqk.class, new ppk(1))));
    public static final jp6 c = new jp6("eventName", p.h(ewi.g(xqk.class, new ppk(2))));
    public static final jp6 d = new jp6("isThickClient", p.h(ewi.g(xqk.class, new ppk(37))));
    public static final jp6 e = new jp6("clientType", p.h(ewi.g(xqk.class, new ppk(61))));
    public static final jp6 f = new jp6("modelDownloadLogEvent", p.h(ewi.g(xqk.class, new ppk(3))));
    public static final jp6 g = new jp6("customModelLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(20))));
    public static final jp6 h = new jp6("customModelInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(4))));
    public static final jp6 i = new jp6("customModelCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(29))));
    public static final jp6 j = new jp6("onDeviceFaceDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(5))));
    public static final jp6 k = new jp6("onDeviceFaceLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(59))));
    public static final jp6 l = new jp6("onDeviceTextDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(6))));
    public static final jp6 m = new jp6("onDeviceTextDetectionLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(79))));
    public static final jp6 n = new jp6("onDeviceBarcodeDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(7))));
    public static final jp6 o = new jp6("onDeviceBarcodeLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(58))));
    public static final jp6 p = new jp6("onDeviceImageLabelCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(48))));
    public static final jp6 q = new jp6("onDeviceImageLabelLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(49))));
    public static final jp6 r = new jp6("onDeviceImageLabelDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(18))));
    public static final jp6 s = new jp6("onDeviceObjectCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(26))));
    public static final jp6 t = new jp6("onDeviceObjectLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(27))));
    public static final jp6 u = new jp6("onDeviceObjectInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(28))));
    public static final jp6 v = new jp6("onDevicePoseDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(44))));
    public static final jp6 w = new jp6("onDeviceSegmentationLogEvent", p.h(ewi.g(xqk.class, new ppk(45))));
    public static final jp6 x = new jp6("onDeviceSmartReplyLogEvent", p.h(ewi.g(xqk.class, new ppk(19))));
    public static final jp6 y = new jp6("onDeviceLanguageIdentificationLogEvent", p.h(ewi.g(xqk.class, new ppk(21))));
    public static final jp6 z = new jp6("onDeviceTranslationLogEvent", p.h(ewi.g(xqk.class, new ppk(22))));
    public static final jp6 A = new jp6("cloudFaceDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(8))));
    public static final jp6 B = new jp6("cloudCropHintDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(9))));
    public static final jp6 C = new jp6("cloudDocumentTextDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(10))));
    public static final jp6 D = new jp6("cloudImagePropertiesDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(11))));
    public static final jp6 E = new jp6("cloudImageLabelDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(12))));
    public static final jp6 F = new jp6("cloudLandmarkDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(13))));
    public static final jp6 G = new jp6("cloudLogoDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(14))));
    public static final jp6 H = new jp6("cloudSafeSearchDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(15))));
    public static final jp6 I = new jp6("cloudTextDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(16))));
    public static final jp6 J = new jp6("cloudWebSearchDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(17))));
    public static final jp6 K = new jp6("automlImageLabelingCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(23))));
    public static final jp6 L = new jp6("automlImageLabelingLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(24))));
    public static final jp6 M = new jp6("automlImageLabelingInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(25))));
    public static final jp6 N = new jp6("isModelDownloadedLogEvent", p.h(ewi.g(xqk.class, new ppk(39))));
    public static final jp6 O = new jp6("deleteModelLogEvent", p.h(ewi.g(xqk.class, new ppk(40))));
    public static final jp6 P = new jp6("aggregatedAutomlImageLabelingInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(30))));
    public static final jp6 Q = new jp6("aggregatedCustomModelInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(31))));
    public static final jp6 R = new jp6("aggregatedOnDeviceFaceDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(32))));
    public static final jp6 S = new jp6("aggregatedOnDeviceBarcodeDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(33))));
    public static final jp6 T = new jp6("aggregatedOnDeviceImageLabelDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(34))));
    public static final jp6 U = new jp6("aggregatedOnDeviceObjectInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(35))));
    public static final jp6 V = new jp6("aggregatedOnDeviceTextDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(36))));
    public static final jp6 W = new jp6("aggregatedOnDevicePoseDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(46))));
    public static final jp6 X = new jp6("aggregatedOnDeviceSegmentationLogEvent", p.h(ewi.g(xqk.class, new ppk(47))));
    public static final jp6 Y = new jp6("pipelineAccelerationInferenceEvents", p.h(ewi.g(xqk.class, new ppk(69))));
    public static final jp6 Z = new jp6("remoteConfigLogEvent", p.h(ewi.g(xqk.class, new ppk(42))));
    public static final jp6 a0 = new jp6("inputImageConstructionLogEvent", p.h(ewi.g(xqk.class, new ppk(50))));
    public static final jp6 b0 = new jp6("leakedHandleEvent", p.h(ewi.g(xqk.class, new ppk(51))));
    public static final jp6 c0 = new jp6("cameraSourceLogEvent", p.h(ewi.g(xqk.class, new ppk(52))));
    public static final jp6 d0 = new jp6("imageLabelOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(53))));
    public static final jp6 e0 = new jp6("languageIdentificationOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(54))));
    public static final jp6 f0 = new jp6("faceDetectionOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(60))));
    public static final jp6 g0 = new jp6("documentDetectionOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(85))));
    public static final jp6 h0 = new jp6("documentCroppingOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(86))));
    public static final jp6 i0 = new jp6("documentEnhancementOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(87))));
    public static final jp6 j0 = new jp6("nlClassifierOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(55))));
    public static final jp6 k0 = new jp6("nlClassifierClientLibraryLogEvent", p.h(ewi.g(xqk.class, new ppk(56))));
    public static final jp6 l0 = new jp6("accelerationAllowlistLogEvent", p.h(ewi.g(xqk.class, new ppk(57))));
    public static final jp6 m0 = new jp6("toxicityDetectionCreateEvent", p.h(ewi.g(xqk.class, new ppk(62))));
    public static final jp6 n0 = new jp6("toxicityDetectionLoadEvent", p.h(ewi.g(xqk.class, new ppk(63))));
    public static final jp6 o0 = new jp6("toxicityDetectionInferenceEvent", p.h(ewi.g(xqk.class, new ppk(64))));
    public static final jp6 p0 = new jp6("barcodeDetectionOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(65))));
    public static final jp6 q0 = new jp6("customImageLabelOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(66))));
    public static final jp6 r0 = new jp6("codeScannerScanApiEvent", p.h(ewi.g(xqk.class, new ppk(67))));
    public static final jp6 s0 = new jp6("codeScannerOptionalModuleEvent", p.h(ewi.g(xqk.class, new ppk(68))));
    public static final jp6 t0 = new jp6("onDeviceExplicitContentCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(70))));
    public static final jp6 u0 = new jp6("onDeviceExplicitContentLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(71))));
    public static final jp6 v0 = new jp6("onDeviceExplicitContentInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(72))));
    public static final jp6 w0 = new jp6("aggregatedOnDeviceExplicitContentLogEvent", p.h(ewi.g(xqk.class, new ppk(73))));
    public static final jp6 x0 = new jp6("onDeviceFaceMeshCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(74))));
    public static final jp6 y0 = new jp6("onDeviceFaceMeshLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(75))));
    public static final jp6 z0 = new jp6("onDeviceFaceMeshLogEvent", p.h(ewi.g(xqk.class, new ppk(76))));
    public static final jp6 A0 = new jp6("aggregatedOnDeviceFaceMeshLogEvent", p.h(ewi.g(xqk.class, new ppk(77))));
    public static final jp6 B0 = new jp6("smartReplyOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(78))));
    public static final jp6 C0 = new jp6("textDetectionOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(80))));
    public static final jp6 D0 = new jp6("onDeviceImageQualityAnalysisCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(81))));
    public static final jp6 E0 = new jp6("onDeviceImageQualityAnalysisLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(82))));
    public static final jp6 F0 = new jp6("onDeviceImageQualityAnalysisLogEvent", p.h(ewi.g(xqk.class, new ppk(83))));
    public static final jp6 G0 = new jp6("aggregatedOnDeviceImageQualityAnalysisLogEvent", p.h(ewi.g(xqk.class, new ppk(84))));
    public static final jp6 H0 = new jp6("imageQualityAnalysisOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(88))));
    public static final jp6 I0 = new jp6("imageCaptioningOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(89))));
    public static final jp6 J0 = new jp6("onDeviceImageCaptioningCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(90))));
    public static final jp6 K0 = new jp6("onDeviceImageCaptioningLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(91))));
    public static final jp6 L0 = new jp6("onDeviceImageCaptioningInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(92))));
    public static final jp6 M0 = new jp6("aggregatedOnDeviceImageCaptioningInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(93))));
    public static final jp6 N0 = new jp6("onDeviceDocumentDetectionCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(94))));
    public static final jp6 O0 = new jp6("onDeviceDocumentDetectionLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(95))));
    public static final jp6 P0 = new jp6("onDeviceDocumentDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(96))));
    public static final jp6 Q0 = new jp6("aggregatedOnDeviceDocumentDetectionLogEvent", p.h(ewi.g(xqk.class, new ppk(97))));
    public static final jp6 R0 = new jp6("onDeviceDocumentCroppingCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(98))));
    public static final jp6 S0 = new jp6("onDeviceDocumentCroppingLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(99))));
    public static final jp6 T0 = new jp6("onDeviceDocumentCroppingLogEvent", p.h(ewi.g(xqk.class, new ppk(100))));
    public static final jp6 U0 = new jp6("aggregatedOnDeviceDocumentCroppingLogEvent", p.h(ewi.g(xqk.class, new ppk(101))));
    public static final jp6 V0 = new jp6("onDeviceDocumentEnhancementCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(102))));
    public static final jp6 W0 = new jp6("onDeviceDocumentEnhancementLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(AidlException.HOST_IS_NOT_MASTER))));
    public static final jp6 X0 = new jp6("onDeviceDocumentEnhancementLogEvent", p.h(ewi.g(xqk.class, new ppk(AidlException.SDK_IS_NOT_INITIALIZED))));
    public static final jp6 Y0 = new jp6("aggregatedOnDeviceDocumentEnhancementLogEvent", p.h(ewi.g(xqk.class, new ppk(AidlException.TRANSFERRED_IPC_DATA_EXCEPTION))));
    public static final jp6 Z0 = new jp6("scannerAutoZoomEvent", p.h(ewi.g(xqk.class, new ppk(106))));
    public static final jp6 a1 = new jp6("lowLightAutoExposureComputationEvent", p.h(ewi.g(xqk.class, new ppk(107))));
    public static final jp6 b1 = new jp6("lowLightFrameProcessEvent", p.h(ewi.g(xqk.class, new ppk(108))));
    public static final jp6 c1 = new jp6("lowLightSceneDetectionEvent", p.h(ewi.g(xqk.class, new ppk(109))));
    public static final jp6 d1 = new jp6("onDeviceStainRemovalLogEvent", p.h(ewi.g(xqk.class, new ppk(110))));
    public static final jp6 e1 = new jp6("aggregatedOnDeviceStainRemovalLogEvent", p.h(ewi.g(xqk.class, new ppk(111))));
    public static final jp6 f1 = new jp6("stainRemovalOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(112))));
    public static final jp6 g1 = new jp6("onDeviceShadowRemovalLogEvent", p.h(ewi.g(xqk.class, new ppk(113))));
    public static final jp6 h1 = new jp6("aggregatedOnDeviceShadowRemovalLogEvent", p.h(ewi.g(xqk.class, new ppk(114))));
    public static final jp6 i1 = new jp6("shadowRemovalOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(115))));
    public static final jp6 j1 = new jp6("onDeviceDigitalInkSegmentationLogEvent", p.h(ewi.g(xqk.class, new ppk(116))));
    public static final jp6 k1 = new jp6("onDeviceDocumentScannerStartLogEvent", p.h(ewi.g(xqk.class, new ppk(117))));
    public static final jp6 l1 = new jp6("onDeviceDocumentScannerFinishLogEvent", p.h(ewi.g(xqk.class, new ppk(118))));
    public static final jp6 m1 = new jp6("onDeviceDocumentScannerUiStartLogEvent", p.h(ewi.g(xqk.class, new ppk(119))));
    public static final jp6 n1 = new jp6("onDeviceDocumentScannerUiFinishLogEvent", p.h(ewi.g(xqk.class, new ppk(120))));
    public static final jp6 o1 = new jp6("documentScannerUiOptionalModuleSessionStartLogEvent", p.h(ewi.g(xqk.class, new ppk(121))));
    public static final jp6 p1 = new jp6("documentScannerUiOptionalModuleSessionFinishLogEvent", p.h(ewi.g(xqk.class, new ppk(122))));
    public static final jp6 q1 = new jp6("onDeviceDocumentScannerUiCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(123))));
    public static final jp6 r1 = new jp6("onDeviceSubjectSegmentationCreateLogEvent", p.h(ewi.g(xqk.class, new ppk(124))));
    public static final jp6 s1 = new jp6("onDeviceSubjectSegmentationLoadLogEvent", p.h(ewi.g(xqk.class, new ppk(125))));
    public static final jp6 t1 = new jp6("onDeviceSubjectSegmentationInferenceLogEvent", p.h(ewi.g(xqk.class, new ppk(126))));
    public static final jp6 u1 = new jp6("aggregatedOnDeviceSubjectSegmentationLogEvent", p.h(ewi.g(xqk.class, new ppk(127))));
    public static final jp6 v1 = new jp6("subjectSegmentationOptionalModuleLogEvent", p.h(ewi.g(xqk.class, new ppk(np0.m))));
    public static final jp6 w1 = new jp6("documentScannerUiModuleScreenViewEvent", p.h(ewi.g(xqk.class, new ppk(129))));
    public static final jp6 x1 = new jp6("documentScannerUiModuleScreenClickEvent", p.h(ewi.g(xqk.class, new ppk(130))));

    static {
        xp9 xp9VarA = jp6.a("documentScannerUiModuleScreenErrorEvent");
        xp9VarA.V(new ppk(131));
        y1 = xp9VarA.K();
    }

    @Override // defpackage.v76
    public final void a(Object obj, Object obj2) {
        gul gulVar = (gul) obj;
        aqb aqbVar = (aqb) obj2;
        aqbVar.a(b, gulVar.a);
        aqbVar.a(c, gulVar.b);
        aqbVar.a(d, null);
        aqbVar.a(e, null);
        aqbVar.a(f, gulVar.c);
        aqbVar.a(g, null);
        aqbVar.a(h, null);
        aqbVar.a(i, null);
        aqbVar.a(j, null);
        aqbVar.a(k, null);
        aqbVar.a(l, null);
        aqbVar.a(m, null);
        aqbVar.a(n, null);
        aqbVar.a(o, null);
        aqbVar.a(p, null);
        aqbVar.a(q, null);
        aqbVar.a(r, null);
        aqbVar.a(s, null);
        aqbVar.a(t, null);
        aqbVar.a(u, null);
        aqbVar.a(v, null);
        aqbVar.a(w, null);
        aqbVar.a(x, null);
        aqbVar.a(y, null);
        aqbVar.a(z, null);
        aqbVar.a(A, null);
        aqbVar.a(B, null);
        aqbVar.a(C, null);
        aqbVar.a(D, null);
        aqbVar.a(E, null);
        aqbVar.a(F, null);
        aqbVar.a(G, null);
        aqbVar.a(H, null);
        aqbVar.a(I, null);
        aqbVar.a(J, null);
        aqbVar.a(K, null);
        aqbVar.a(L, null);
        aqbVar.a(M, null);
        aqbVar.a(N, gulVar.d);
        aqbVar.a(O, gulVar.e);
        aqbVar.a(P, null);
        aqbVar.a(Q, null);
        aqbVar.a(R, null);
        aqbVar.a(S, null);
        aqbVar.a(T, null);
        aqbVar.a(U, null);
        aqbVar.a(V, null);
        aqbVar.a(W, null);
        aqbVar.a(X, null);
        aqbVar.a(Y, null);
        aqbVar.a(Z, null);
        aqbVar.a(a0, null);
        aqbVar.a(b0, gulVar.f);
        aqbVar.a(c0, null);
        aqbVar.a(d0, null);
        aqbVar.a(e0, null);
        aqbVar.a(f0, null);
        aqbVar.a(g0, null);
        aqbVar.a(h0, null);
        aqbVar.a(i0, null);
        aqbVar.a(j0, null);
        aqbVar.a(k0, null);
        aqbVar.a(l0, null);
        aqbVar.a(m0, null);
        aqbVar.a(n0, null);
        aqbVar.a(o0, null);
        aqbVar.a(p0, null);
        aqbVar.a(q0, null);
        aqbVar.a(r0, null);
        aqbVar.a(s0, null);
        aqbVar.a(t0, null);
        aqbVar.a(u0, null);
        aqbVar.a(v0, null);
        aqbVar.a(w0, null);
        aqbVar.a(x0, null);
        aqbVar.a(y0, null);
        aqbVar.a(z0, null);
        aqbVar.a(A0, null);
        aqbVar.a(B0, null);
        aqbVar.a(C0, null);
        aqbVar.a(D0, null);
        aqbVar.a(E0, null);
        aqbVar.a(F0, null);
        aqbVar.a(G0, null);
        aqbVar.a(H0, null);
        aqbVar.a(I0, null);
        aqbVar.a(J0, null);
        aqbVar.a(K0, null);
        aqbVar.a(L0, null);
        aqbVar.a(M0, null);
        aqbVar.a(N0, null);
        aqbVar.a(O0, null);
        aqbVar.a(P0, null);
        aqbVar.a(Q0, null);
        aqbVar.a(R0, null);
        aqbVar.a(S0, null);
        aqbVar.a(T0, null);
        aqbVar.a(U0, null);
        aqbVar.a(V0, null);
        aqbVar.a(W0, null);
        aqbVar.a(X0, null);
        aqbVar.a(Y0, null);
        aqbVar.a(Z0, null);
        aqbVar.a(a1, null);
        aqbVar.a(b1, null);
        aqbVar.a(c1, null);
        aqbVar.a(d1, null);
        aqbVar.a(e1, null);
        aqbVar.a(f1, null);
        aqbVar.a(g1, null);
        aqbVar.a(h1, null);
        aqbVar.a(i1, null);
        aqbVar.a(j1, null);
        aqbVar.a(k1, null);
        aqbVar.a(l1, null);
        aqbVar.a(m1, null);
        aqbVar.a(n1, null);
        aqbVar.a(o1, null);
        aqbVar.a(p1, null);
        aqbVar.a(q1, null);
        aqbVar.a(r1, null);
        aqbVar.a(s1, null);
        aqbVar.a(t1, null);
        aqbVar.a(u1, null);
        aqbVar.a(v1, null);
        aqbVar.a(w1, null);
        aqbVar.a(x1, null);
        aqbVar.a(y1, null);
    }
}
