package defpackage;

import com.vk.push.core.base.AidlException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashMap;
import java.util.Map;
import org.apache.http.HttpStatus;

/* JADX INFO: loaded from: classes.dex */
public final class xk5 implements af7 {
    public static final ArrayList e = new ArrayList();
    public final ha9 a;
    public final String b = "https";
    public final String c = "max.ru";
    public final af7 d;

    public xk5(ha9 ha9Var, t5 t5Var) {
        this.a = ha9Var;
        this.d = t5Var;
    }

    public final void a() {
        Object value;
        LinkedHashMap linkedHashMap;
        try {
            gdi gdiVar = new gdi("app-scope");
            r3f r3fVar = wk8.e;
            if (r3fVar == null) {
                throw new IllegalArgumentException("Root scope not initialized!");
            }
            gdiVar.c.add(r3fVar);
            gdiVar.d(30, new wk5(0, this));
            oc9.h0(gdiVar);
            int i = 1;
            gdiVar.d(0, new l65(i));
            gm0.Q(gdiVar);
            gdiVar.d(1134, new b7c(3));
            gdiVar.d(1138, new b7c(4));
            gdiVar.d(1135, new rwb(6));
            gdiVar.d(1136, new rwb(7));
            gdiVar.d(8, new b7c(15));
            gdiVar.d(1, new b7c(16));
            gdiVar.d(46, new b7c(17));
            gdiVar.d(672, new qqg(19));
            gdiVar.d(668, new qqg(20));
            ixb.a(gdiVar, this.b, this.c);
            gdiVar.d(100, new g(2));
            wxb wxbVar = wxb.a;
            qe7.U(gdiVar);
            cqk.P(gdiVar);
            gdiVar.b(3, new f(0));
            gdiVar.d(HttpStatus.SC_TEMPORARY_REDIRECT, new g(0));
            sb8.r0(gdiVar);
            gdiVar.b(3, new f(8));
            gdiVar.d(937, new g(27));
            f55.I(gdiVar);
            ch3.j0(gdiVar);
            gdiVar.b(3, new f(7));
            int i2 = 28;
            gdiVar.d(AidlException.SDK_IS_NOT_INITIALIZED, new g(28));
            qe7.Q(gdiVar);
            ch3.i0(gdiVar);
            qe7.R(gdiVar);
            gdiVar.d(349, new fc1(23));
            np4.J(gdiVar);
            gdiVar.d(1093, new t62(i));
            gdiVar.d(736, new t62(2));
            gdiVar.d(875, new t62(3));
            gm0.O(gdiVar);
            gdiVar.d(1014, new fc1(27));
            gdiVar.b(3, new f(23));
            gdiVar.d(1015, new cp0(23));
            n1g.g0(gdiVar);
            gm0.S(gdiVar);
            cqk.O(gdiVar);
            f55.J(gdiVar);
            gdiVar.b(3, new lu2(13));
            gdiVar.d(301, new mu2(11));
            gdiVar.d(HttpStatus.SC_MOVED_TEMPORARILY, new ci3(10));
            gdiVar.b(3, new lu2(15));
            gdiVar.d(942, new ci3(25));
            gdiVar.d(943, new ci3(26));
            gdiVar.d(769, new ci3(27));
            gdiVar.b(3, new lu2(14));
            gdiVar.d(HttpStatus.SC_USE_PROXY, new ci3(22));
            gdiVar.d(181, new i35(28));
            gdiVar.d(182, new i35(29));
            oc9.g0(gdiVar);
            gdiVar.b(4, new gj5(4));
            gdiVar.b(4, new gj5(5));
            gdiVar.b(4, new gj5(6));
            gdiVar.b(3, new gj5(7));
            gdiVar.d(293, new l65(8));
            np4.K(gdiVar);
            vd7.N(gdiVar);
            sb8.s0(gdiVar);
            gdiVar.d(31, new l65(i2));
            gdiVar.d(32, new mu2(22));
            gdiVar.d(121, new mu2(23));
            wk8.F(gdiVar);
            rx8.n0(gdiVar);
            gdiVar.d(AidlException.HOST_IS_NOT_MASTER, new wk5(2, new i94(14)));
            gdiVar.b(3, new gj5(20));
            gdiVar.d(754, new gj5(21));
            gdiVar.d(767, new ko7(11));
            gdiVar.d(768, new ko7(12));
            gdiVar.d(310, new ko7(5));
            gdiVar.d(214, new mu2(27));
            gdiVar.d(215, new gj5(22));
            gdiVar.d(216, new gj5(23));
            gdiVar.d(217, new mu2(28));
            gdiVar.b(3, new gj5(24));
            gdiVar.d(760, new ko7(28));
            gdiVar.d(761, new ko7(29));
            gdiVar.d(762, new zc9(0));
            vd7.O(gdiVar);
            gdiVar.b(3, new gj5(26));
            gdiVar.d(1063, new zc9(9));
            gdiVar.b(3, new gj5(27));
            qe7.S(gdiVar);
            gdiVar.d(127, new zc9(12));
            gdiVar.d(np0.m, new zc9(13));
            gdiVar.d(129, new zc9(14));
            gdiVar.d(130, new zc9(15));
            gdiVar.d(781, new l65(29));
            sb8.t0(gdiVar);
            wk8.G(gdiVar);
            gdiVar.d(50, new zc9(18));
            gdiVar.d(51, new nx9(4));
            gdiVar.d(52, new zc9(19));
            gdiVar.d(53, new zc9(20));
            gdiVar.d(755, new lf9(17));
            gdiVar.d(756, new lf9(18));
            gdiVar.d(757, new zc9(21));
            gdiVar.d(758, new zc9(22));
            gdiVar.d(167, new nx9(6));
            gdiVar.d(171, new lf9(19));
            ch3.h0(gdiVar);
            rx8.o0(gdiVar);
            gdiVar.d(np0.n, new zc9(16));
            gdiVar.d(257, new lf9(6));
            gdiVar.d(258, new lf9(7));
            gdiVar.d(259, new lf9(8));
            gdiVar.b(3, new nx9(5));
            gm0.P(gdiVar);
            gdiVar.d(34, new b7c(18));
            gdiVar.d(344, new rwb(9));
            gdiVar.d(345, new pwb(5));
            gdiVar.d(346, new b7c(19));
            gdiVar.d(929, new b7c(20));
            gdiVar.d(930, new m3d(4));
            yab.I0(gdiVar);
            sb8.u0(gdiVar);
            vd7.P(gdiVar);
            qe7.T(gdiVar);
            gdiVar.d(175, new jld(10));
            gdiVar.b(3, new pwb(17));
            gdiVar.d(320, new jnd(3));
            gdiVar.d(321, new jnd(4));
            gdiVar.d(123, new g7f(16));
            gdiVar.d(124, new g7f(17));
            gdiVar.d(125, new g7f(18));
            gdiVar.d(126, new g7f(19));
            sb8.v0(gdiVar);
            gm0.R(gdiVar);
            gdiVar.d(308, new g7f(23));
            gdiVar.b(3, new y6f(24));
            np4.L(gdiVar);
            f55.K(gdiVar);
            gdiVar.d(807, new g7f(25));
            gdiVar.b(3, new y6f(25));
            gdiVar.d(808, new eaf(4));
            gdiVar.d(366, new eaf(10));
            gdiVar.b(3, new y6f(29));
            gdiVar.d(314, new g7f(i2));
            gdiVar.b(3, new bwf(0));
            np4.M(gdiVar);
            gdiVar.b(3, new bwf(1));
            gdiVar.d(1013, new eaf(11));
            gdiVar.b(3, new bwf(2));
            gdiVar.d(263, new bwf(3));
            gdiVar.b(4, new bwf(4));
            gdiVar.b(3, new bwf(6));
            gdiVar.d(1020, new eaf(12));
            gdiVar.d(1021, new eaf(13));
            gdiVar.d(1022, new vfg(3));
            lvb.F0(gdiVar);
            gdiVar.b(3, new bwf(9));
            gdiVar.d(HttpStatus.SC_BAD_REQUEST, new vfg(26));
            gdiVar.d(354, new zc9(17));
            gdiVar.d(361, new vfg(25));
            gdiVar.d(359, new eaf(15));
            gdiVar.b(3, new bwf(10));
            gdiVar.d(364, new vfg(27));
            gdiVar.b(3, new bwf(11));
            gdiVar.d(398, new vfg(28));
            gdiVar.d(399, new vfg(29));
            gdiVar.b(3, new bwf(12));
            gdiVar.d(380, new bwf(13));
            gdiVar.d(381, new eaf(16));
            qe7.V(gdiVar);
            wk8.I(gdiVar);
            gdiVar.d(89, new jld(18));
            gdiVar.d(98, new jnd(5));
            gdiVar.d(94, new jnd(6));
            cqk.Q(gdiVar);
            gdiVar.b(3, new m3i(21));
            gdiVar.d(209, new m3i(22));
            gdiVar.d(208, new kdj(5));
            gdiVar.d(210, new kdj(6));
            yab.J0(gdiVar);
            gdiVar.d(351, new r1i(8));
            gdiVar.b(4, new m3i(0));
            wk8.H(gdiVar);
            gdiVar.d(298, new m3d(8));
            gdiVar.d(297, new m3d(7));
            gdiVar.d(299, new rwb(11));
            gdiVar.d(117, new bwf(25));
            gdiVar.d(118, new bwf(26));
            gdiVar.d(119, new bwf(27));
            p90.S(gdiVar);
            ch3.k0(gdiVar);
            gdiVar.d(2, new wk5(3, this.d));
            gdiVar.d(3, new vfg(2));
            gdiVar.d(4, new vfg(0));
            gdiVar.d(5, new vfg(1));
            gdiVar.d(6, new bwf(5));
            gdiVar.d(180, new zc9(29));
            Iterator it = e.iterator();
            while (it.hasNext()) {
                ((cf7) it.next()).invoke(gdiVar);
            }
            r3f r3fVarA = gdiVar.a();
            r7 r7Var = r7.a;
            ha9 ha9Var = this.a;
            mjg mjgVar = r7.b;
            do {
                value = mjgVar.getValue();
                linkedHashMap = new LinkedHashMap((Map) value);
                linkedHashMap.put(ha9Var, new y6(r3fVarA));
            } while (!mjgVar.h(value, linkedHashMap));
        } catch (Throwable unused) {
        }
    }

    @Override // defpackage.af7
    public final /* bridge */ /* synthetic */ Object invoke() {
        a();
        return sbi.a;
    }
}
