package defpackage;

import java.util.ArrayList;
import java.util.List;

/* JADX INFO: loaded from: classes3.dex */
public final /* synthetic */ class xna implements cf7 {
    public final /* synthetic */ int a;
    public final /* synthetic */ long b;
    public final /* synthetic */ toa c;
    public final /* synthetic */ wja d;

    public /* synthetic */ xna(long j, toa toaVar, wja wjaVar, int i) {
        this.a = i;
        this.b = j;
        this.c = toaVar;
        this.d = wjaVar;
    }

    private final Object a(Object obj) throws Exception {
        long j = this.b;
        toa toaVar = this.c;
        wja wjaVar = this.d;
        vxe vxeVarO0 = ((qxe) obj).O0("SELECT * FROM messages WHERE chat_id = ? AND inserted_from_msg_link = 0 AND status <> ? AND delayed_attrs_time_to_fire IS NULL AND delayed_attrs_notify_sender IS NULL ORDER BY time DESC LIMIT ?");
        try {
            vxeVarO0.c(1, j);
            toaVar.e().getClass();
            vxeVarO0.c(2, wjaVar.a);
            vxeVarO0.c(3, 1L);
            int iE = qyj.E(vxeVarO0, "id");
            int iE2 = qyj.E(vxeVarO0, "server_id");
            int iE3 = qyj.E(vxeVarO0, "time");
            int iE4 = qyj.E(vxeVarO0, "update_time");
            int iE5 = qyj.E(vxeVarO0, "sender");
            int iE6 = qyj.E(vxeVarO0, "cid");
            int iE7 = qyj.E(vxeVarO0, "text");
            int iE8 = qyj.E(vxeVarO0, "delivery_status");
            int iE9 = qyj.E(vxeVarO0, "status");
            int iE10 = qyj.E(vxeVarO0, "status_in_process");
            int iE11 = qyj.E(vxeVarO0, "time_local");
            int iE12 = qyj.E(vxeVarO0, "error");
            int iE13 = qyj.E(vxeVarO0, "localized_error");
            int iE14 = qyj.E(vxeVarO0, "attaches");
            int iE15 = qyj.E(vxeVarO0, "media_type");
            int iE16 = qyj.E(vxeVarO0, "detect_share");
            int iE17 = qyj.E(vxeVarO0, "msg_link_type");
            int iE18 = qyj.E(vxeVarO0, "msg_link_id");
            int iE19 = qyj.E(vxeVarO0, "inserted_from_msg_link");
            int iE20 = qyj.E(vxeVarO0, "msg_link_chat_id");
            int iE21 = qyj.E(vxeVarO0, "msg_link_chat_name");
            int iE22 = qyj.E(vxeVarO0, "msg_link_chat_link");
            int iE23 = qyj.E(vxeVarO0, "msg_link_chat_icon_url");
            int iE24 = qyj.E(vxeVarO0, "msg_link_chat_access_type");
            int iE25 = qyj.E(vxeVarO0, "msg_link_out_chat_id");
            int iE26 = qyj.E(vxeVarO0, "msg_link_out_msg_id");
            int iE27 = qyj.E(vxeVarO0, "type");
            int iE28 = qyj.E(vxeVarO0, "chat_id");
            int iE29 = qyj.E(vxeVarO0, "channel_views");
            int iE30 = qyj.E(vxeVarO0, "channel_forwards");
            int iE31 = qyj.E(vxeVarO0, "view_time");
            int iE32 = qyj.E(vxeVarO0, "options");
            int iE33 = qyj.E(vxeVarO0, "live_until");
            int iE34 = qyj.E(vxeVarO0, "elements");
            int iE35 = qyj.E(vxeVarO0, "reactions");
            int iE36 = qyj.E(vxeVarO0, "delayed_attrs_time_to_fire");
            int iE37 = qyj.E(vxeVarO0, "delayed_attrs_notify_sender");
            int iE38 = qyj.E(vxeVarO0, "reactions_update_time");
            ArrayList arrayList = new ArrayList();
            while (vxeVarO0.M0()) {
                long j2 = vxeVarO0.getLong(iE);
                long j3 = vxeVarO0.getLong(iE2);
                long j4 = vxeVarO0.getLong(iE3);
                long j5 = vxeVarO0.getLong(iE4);
                long j6 = vxeVarO0.getLong(iE5);
                long j7 = vxeVarO0.getLong(iE6);
                Boolean boolValueOf = null;
                String strB0 = vxeVarO0.isNull(iE7) ? null : vxeVarO0.B0(iE7);
                int i = (int) vxeVarO0.getLong(iE8);
                toaVar.e().getClass();
                xfa xfaVarB = dwa.b(i);
                int i2 = (int) vxeVarO0.getLong(iE9);
                toaVar.e().getClass();
                wja wjaVarD = dwa.d(i2);
                boolean z = ((int) vxeVarO0.getLong(iE10)) != 0;
                long j8 = vxeVarO0.getLong(iE11);
                String strB1 = vxeVarO0.isNull(iE12) ? null : vxeVarO0.B0(iE12);
                String strB2 = vxeVarO0.isNull(iE13) ? null : vxeVarO0.B0(iE13);
                byte[] blob = vxeVarO0.isNull(iE14) ? null : vxeVarO0.getBlob(iE14);
                toaVar.e().getClass();
                c46 c46VarA = dwa.a(blob);
                int i3 = iE15;
                int i4 = iE3;
                int i5 = (int) vxeVarO0.getLong(i3);
                int i6 = iE16;
                boolean z2 = ((int) vxeVarO0.getLong(i6)) != 0;
                int i7 = iE17;
                int i8 = (int) vxeVarO0.getLong(i7);
                int i9 = iE18;
                long j9 = vxeVarO0.getLong(i9);
                int i10 = iE19;
                boolean z3 = ((int) vxeVarO0.getLong(i10)) != 0;
                int i11 = iE20;
                long j10 = vxeVarO0.getLong(i11);
                int i12 = iE21;
                String strB3 = vxeVarO0.isNull(i12) ? null : vxeVarO0.B0(i12);
                int i13 = iE22;
                String strB4 = vxeVarO0.isNull(i13) ? null : vxeVarO0.B0(i13);
                iE22 = i13;
                int i14 = iE23;
                String strB5 = vxeVarO0.isNull(i14) ? null : vxeVarO0.B0(i14);
                iE23 = i14;
                int i15 = iE24;
                Integer numValueOf = vxeVarO0.isNull(i15) ? null : Integer.valueOf((int) vxeVarO0.getLong(i15));
                toaVar.d().getClass();
                int iA = vo3.a(numValueOf);
                int i16 = iE25;
                long j11 = vxeVarO0.getLong(i16);
                int i17 = iE26;
                long j12 = vxeVarO0.getLong(i17);
                int i18 = iE27;
                int i19 = (int) vxeVarO0.getLong(i18);
                toaVar.e().getClass();
                int iE39 = dwa.e(i19);
                int i20 = iE28;
                long j13 = vxeVarO0.getLong(i20);
                int i21 = iE29;
                int i22 = (int) vxeVarO0.getLong(i21);
                int i23 = iE14;
                int i24 = iE30;
                int i25 = iE4;
                int i26 = (int) vxeVarO0.getLong(i24);
                int i27 = iE31;
                long j14 = vxeVarO0.getLong(i27);
                int i28 = iE32;
                int i29 = (int) vxeVarO0.getLong(i28);
                int i30 = iE33;
                long j15 = vxeVarO0.getLong(i30);
                int i31 = iE34;
                byte[] blob2 = vxeVarO0.getBlob(i31);
                toaVar.e().getClass();
                List listC = dwa.c(blob2);
                iE34 = i31;
                int i32 = iE35;
                kja kjaVarF = toaVar.e().f(vxeVarO0.isNull(i32) ? null : vxeVarO0.getBlob(i32));
                int i33 = iE36;
                Long lValueOf = vxeVarO0.isNull(i33) ? null : Long.valueOf(vxeVarO0.getLong(i33));
                int i34 = iE37;
                Integer numValueOf2 = vxeVarO0.isNull(i34) ? null : Integer.valueOf((int) vxeVarO0.getLong(i34));
                if (numValueOf2 != null) {
                    boolValueOf = Boolean.valueOf(numValueOf2.intValue() != 0);
                }
                int i35 = iE38;
                arrayList.add(new gga(j2, j3, j4, j5, j6, j7, strB0, xfaVarB, wjaVarD, z, j8, strB1, strB2, c46VarA, i5, z2, i8, j9, z3, j10, strB3, strB4, strB5, iA, j11, j12, iE39, j13, i22, i26, j14, i29, j15, listC, kjaVarF, lValueOf, boolValueOf, vxeVarO0.getLong(i35)));
                iE36 = i33;
                iE37 = i34;
                iE38 = i35;
                iE19 = i10;
                iE20 = i11;
                iE21 = i12;
                iE24 = i15;
                iE25 = i16;
                iE26 = i17;
                iE27 = i18;
                iE28 = i20;
                iE4 = i25;
                iE29 = i21;
                iE30 = i24;
                iE32 = i28;
                iE31 = i27;
                iE = iE;
                iE2 = iE2;
                iE14 = i23;
                iE35 = i32;
                iE33 = i30;
                iE3 = i4;
                iE15 = i3;
                iE16 = i6;
                iE17 = i7;
                iE18 = i9;
            }
            return arrayList;
        } finally {
            vxeVarO0.close();
        }
    }

    @Override // defpackage.cf7
    public final Object invoke(Object obj) throws Exception {
        Boolean boolValueOf;
        Boolean boolValueOf2;
        int i = this.a;
        wja wjaVar = this.d;
        toa toaVar = this.c;
        long j = this.b;
        switch (i) {
            case 0:
                vxe vxeVarO0 = ((qxe) obj).O0("SELECT * FROM messages WHERE chat_id = ? AND inserted_from_msg_link = 0 AND status <> ? AND delayed_attrs_time_to_fire IS NOT NULL AND delayed_attrs_notify_sender IS NOT NULL ORDER BY delayed_attrs_time_to_fire ASC LIMIT ?");
                try {
                    vxeVarO0.c(1, j);
                    toaVar.e().getClass();
                    vxeVarO0.c(2, wjaVar.a);
                    vxeVarO0.c(3, 1L);
                    int iE = qyj.E(vxeVarO0, "id");
                    int iE2 = qyj.E(vxeVarO0, "server_id");
                    int iE3 = qyj.E(vxeVarO0, "time");
                    int iE4 = qyj.E(vxeVarO0, "update_time");
                    int iE5 = qyj.E(vxeVarO0, "sender");
                    int iE6 = qyj.E(vxeVarO0, "cid");
                    int iE7 = qyj.E(vxeVarO0, "text");
                    int iE8 = qyj.E(vxeVarO0, "delivery_status");
                    int iE9 = qyj.E(vxeVarO0, "status");
                    int iE10 = qyj.E(vxeVarO0, "status_in_process");
                    int iE11 = qyj.E(vxeVarO0, "time_local");
                    int iE12 = qyj.E(vxeVarO0, "error");
                    int iE13 = qyj.E(vxeVarO0, "localized_error");
                    int iE14 = qyj.E(vxeVarO0, "attaches");
                    int iE15 = qyj.E(vxeVarO0, "media_type");
                    int iE16 = qyj.E(vxeVarO0, "detect_share");
                    int iE17 = qyj.E(vxeVarO0, "msg_link_type");
                    int iE18 = qyj.E(vxeVarO0, "msg_link_id");
                    int iE19 = qyj.E(vxeVarO0, "inserted_from_msg_link");
                    int iE20 = qyj.E(vxeVarO0, "msg_link_chat_id");
                    int iE21 = qyj.E(vxeVarO0, "msg_link_chat_name");
                    int iE22 = qyj.E(vxeVarO0, "msg_link_chat_link");
                    int iE23 = qyj.E(vxeVarO0, "msg_link_chat_icon_url");
                    int iE24 = qyj.E(vxeVarO0, "msg_link_chat_access_type");
                    int iE25 = qyj.E(vxeVarO0, "msg_link_out_chat_id");
                    int iE26 = qyj.E(vxeVarO0, "msg_link_out_msg_id");
                    int iE27 = qyj.E(vxeVarO0, "type");
                    int iE28 = qyj.E(vxeVarO0, "chat_id");
                    int iE29 = qyj.E(vxeVarO0, "channel_views");
                    int iE30 = qyj.E(vxeVarO0, "channel_forwards");
                    int iE31 = qyj.E(vxeVarO0, "view_time");
                    int iE32 = qyj.E(vxeVarO0, "options");
                    int iE33 = qyj.E(vxeVarO0, "live_until");
                    int iE34 = qyj.E(vxeVarO0, "elements");
                    int iE35 = qyj.E(vxeVarO0, "reactions");
                    int iE36 = qyj.E(vxeVarO0, "delayed_attrs_time_to_fire");
                    int iE37 = qyj.E(vxeVarO0, "delayed_attrs_notify_sender");
                    int iE38 = qyj.E(vxeVarO0, "reactions_update_time");
                    ArrayList arrayList = new ArrayList();
                    while (vxeVarO0.M0()) {
                        long j2 = vxeVarO0.getLong(iE);
                        long j3 = vxeVarO0.getLong(iE2);
                        long j4 = vxeVarO0.getLong(iE3);
                        long j5 = vxeVarO0.getLong(iE4);
                        long j6 = vxeVarO0.getLong(iE5);
                        long j7 = vxeVarO0.getLong(iE6);
                        String strB0 = vxeVarO0.isNull(iE7) ? null : vxeVarO0.B0(iE7);
                        int i2 = (int) vxeVarO0.getLong(iE8);
                        toaVar.e().getClass();
                        xfa xfaVarB = dwa.b(i2);
                        int i3 = (int) vxeVarO0.getLong(iE9);
                        toaVar.e().getClass();
                        wja wjaVarD = dwa.d(i3);
                        boolean z = ((int) vxeVarO0.getLong(iE10)) != 0;
                        long j8 = vxeVarO0.getLong(iE11);
                        String strB1 = vxeVarO0.isNull(iE12) ? null : vxeVarO0.B0(iE12);
                        String strB2 = vxeVarO0.isNull(iE13) ? null : vxeVarO0.B0(iE13);
                        byte[] blob = vxeVarO0.isNull(iE14) ? null : vxeVarO0.getBlob(iE14);
                        toaVar.e().getClass();
                        c46 c46VarA = dwa.a(blob);
                        int i4 = iE15;
                        int i5 = iE3;
                        int i6 = (int) vxeVarO0.getLong(i4);
                        int i7 = iE16;
                        boolean z2 = ((int) vxeVarO0.getLong(i7)) != 0;
                        iE16 = i7;
                        int i8 = iE17;
                        int i9 = (int) vxeVarO0.getLong(i8);
                        long j9 = vxeVarO0.getLong(iE18);
                        iE17 = i8;
                        int i10 = iE19;
                        boolean z3 = ((int) vxeVarO0.getLong(i10)) != 0;
                        iE20 = iE20;
                        long j10 = vxeVarO0.getLong(iE20);
                        iE21 = iE21;
                        String strB3 = vxeVarO0.isNull(iE21) ? null : vxeVarO0.B0(iE21);
                        iE19 = i10;
                        int i11 = iE22;
                        String strB4 = vxeVarO0.isNull(i11) ? null : vxeVarO0.B0(i11);
                        iE22 = i11;
                        int i12 = iE23;
                        String strB5 = vxeVarO0.isNull(i12) ? null : vxeVarO0.B0(i12);
                        iE23 = i12;
                        int i13 = iE24;
                        Integer numValueOf = vxeVarO0.isNull(i13) ? null : Integer.valueOf((int) vxeVarO0.getLong(i13));
                        toaVar.d().getClass();
                        int iA = vo3.a(numValueOf);
                        int i14 = iE25;
                        long j11 = vxeVarO0.getLong(i14);
                        int i15 = iE26;
                        long j12 = vxeVarO0.getLong(i15);
                        iE24 = i13;
                        iE25 = i14;
                        iE26 = i15;
                        int i16 = iE27;
                        int i17 = (int) vxeVarO0.getLong(i16);
                        toaVar.e().getClass();
                        int iE39 = dwa.e(i17);
                        int i18 = iE28;
                        long j13 = vxeVarO0.getLong(i18);
                        iE27 = i16;
                        iE28 = i18;
                        int i19 = iE29;
                        int i20 = (int) vxeVarO0.getLong(i19);
                        int i21 = iE11;
                        int i22 = iE30;
                        int i23 = (int) vxeVarO0.getLong(i22);
                        int i24 = iE31;
                        long j14 = vxeVarO0.getLong(i24);
                        int i25 = iE32;
                        int i26 = (int) vxeVarO0.getLong(i25);
                        int i27 = iE33;
                        long j15 = vxeVarO0.getLong(i27);
                        iE32 = i25;
                        int i28 = iE34;
                        byte[] blob2 = vxeVarO0.getBlob(i28);
                        toaVar.e().getClass();
                        List listC = dwa.c(blob2);
                        iE34 = i28;
                        iE35 = iE35;
                        kja kjaVarF = toaVar.e().f(vxeVarO0.isNull(iE35) ? null : vxeVarO0.getBlob(iE35));
                        int i29 = iE36;
                        Long lValueOf = vxeVarO0.isNull(i29) ? null : Long.valueOf(vxeVarO0.getLong(i29));
                        int i30 = iE37;
                        Integer numValueOf2 = vxeVarO0.isNull(i30) ? null : Integer.valueOf((int) vxeVarO0.getLong(i30));
                        if (numValueOf2 != null) {
                            boolValueOf = Boolean.valueOf(numValueOf2.intValue() != 0);
                        } else {
                            boolValueOf = null;
                        }
                        int i31 = iE38;
                        arrayList.add(new gga(j2, j3, j4, j5, j6, j7, strB0, xfaVarB, wjaVarD, z, j8, strB1, strB2, c46VarA, i6, z2, i9, j9, z3, j10, strB3, strB4, strB5, iA, j11, j12, iE39, j13, i20, i23, j14, i26, j15, listC, kjaVarF, lValueOf, boolValueOf, vxeVarO0.getLong(i31)));
                        iE37 = i30;
                        iE38 = i31;
                        iE11 = i21;
                        iE29 = i19;
                        iE30 = i22;
                        iE31 = i24;
                        iE33 = i27;
                        iE2 = iE2;
                        iE3 = i5;
                        iE36 = i29;
                        iE = iE;
                        iE15 = i4;
                        break;
                    }
                    return arrayList;
                } finally {
                    vxeVarO0.close();
                }
            case 1:
                return a(obj);
            default:
                vxe vxeVarO1 = ((qxe) obj).O0("SELECT * FROM messages WHERE chat_id = ? AND inserted_from_msg_link = 0 AND status <> ? AND delayed_attrs_time_to_fire IS NOT NULL AND delayed_attrs_notify_sender IS NOT NULL ORDER BY delayed_attrs_time_to_fire DESC LIMIT ?");
                try {
                    vxeVarO1.c(1, j);
                    toaVar.e().getClass();
                    vxeVarO1.c(2, wjaVar.a);
                    vxeVarO1.c(3, 1L);
                    int iE40 = qyj.E(vxeVarO1, "id");
                    int iE41 = qyj.E(vxeVarO1, "server_id");
                    int iE42 = qyj.E(vxeVarO1, "time");
                    int iE43 = qyj.E(vxeVarO1, "update_time");
                    int iE44 = qyj.E(vxeVarO1, "sender");
                    int iE45 = qyj.E(vxeVarO1, "cid");
                    int iE46 = qyj.E(vxeVarO1, "text");
                    int iE47 = qyj.E(vxeVarO1, "delivery_status");
                    int iE48 = qyj.E(vxeVarO1, "status");
                    int iE49 = qyj.E(vxeVarO1, "status_in_process");
                    int iE50 = qyj.E(vxeVarO1, "time_local");
                    int iE51 = qyj.E(vxeVarO1, "error");
                    int iE52 = qyj.E(vxeVarO1, "localized_error");
                    int iE53 = qyj.E(vxeVarO1, "attaches");
                    int iE54 = qyj.E(vxeVarO1, "media_type");
                    int iE55 = qyj.E(vxeVarO1, "detect_share");
                    int iE56 = qyj.E(vxeVarO1, "msg_link_type");
                    int iE57 = qyj.E(vxeVarO1, "msg_link_id");
                    int iE58 = qyj.E(vxeVarO1, "inserted_from_msg_link");
                    int iE59 = qyj.E(vxeVarO1, "msg_link_chat_id");
                    int iE60 = qyj.E(vxeVarO1, "msg_link_chat_name");
                    int iE61 = qyj.E(vxeVarO1, "msg_link_chat_link");
                    int iE62 = qyj.E(vxeVarO1, "msg_link_chat_icon_url");
                    int iE63 = qyj.E(vxeVarO1, "msg_link_chat_access_type");
                    int iE64 = qyj.E(vxeVarO1, "msg_link_out_chat_id");
                    int iE65 = qyj.E(vxeVarO1, "msg_link_out_msg_id");
                    int iE66 = qyj.E(vxeVarO1, "type");
                    int iE67 = qyj.E(vxeVarO1, "chat_id");
                    int iE68 = qyj.E(vxeVarO1, "channel_views");
                    int iE69 = qyj.E(vxeVarO1, "channel_forwards");
                    int iE70 = qyj.E(vxeVarO1, "view_time");
                    int iE71 = qyj.E(vxeVarO1, "options");
                    int iE72 = qyj.E(vxeVarO1, "live_until");
                    int iE73 = qyj.E(vxeVarO1, "elements");
                    int iE74 = qyj.E(vxeVarO1, "reactions");
                    int iE75 = qyj.E(vxeVarO1, "delayed_attrs_time_to_fire");
                    int iE76 = qyj.E(vxeVarO1, "delayed_attrs_notify_sender");
                    int iE77 = qyj.E(vxeVarO1, "reactions_update_time");
                    ArrayList arrayList2 = new ArrayList();
                    while (vxeVarO1.M0()) {
                        long j16 = vxeVarO1.getLong(iE40);
                        long j17 = vxeVarO1.getLong(iE41);
                        long j18 = vxeVarO1.getLong(iE42);
                        long j19 = vxeVarO1.getLong(iE43);
                        long j20 = vxeVarO1.getLong(iE44);
                        long j21 = vxeVarO1.getLong(iE45);
                        String strB6 = vxeVarO1.isNull(iE46) ? null : vxeVarO1.B0(iE46);
                        int i32 = (int) vxeVarO1.getLong(iE47);
                        toaVar.e().getClass();
                        xfa xfaVarB2 = dwa.b(i32);
                        int i33 = (int) vxeVarO1.getLong(iE48);
                        toaVar.e().getClass();
                        wja wjaVarD2 = dwa.d(i33);
                        boolean z4 = ((int) vxeVarO1.getLong(iE49)) != 0;
                        long j22 = vxeVarO1.getLong(iE50);
                        String strB7 = vxeVarO1.isNull(iE51) ? null : vxeVarO1.B0(iE51);
                        String strB8 = vxeVarO1.isNull(iE52) ? null : vxeVarO1.B0(iE52);
                        byte[] blob3 = vxeVarO1.isNull(iE53) ? null : vxeVarO1.getBlob(iE53);
                        toaVar.e().getClass();
                        c46 c46VarA2 = dwa.a(blob3);
                        int i34 = iE54;
                        int i35 = iE42;
                        int i36 = (int) vxeVarO1.getLong(i34);
                        int i37 = iE55;
                        boolean z5 = ((int) vxeVarO1.getLong(i37)) != 0;
                        int i38 = iE56;
                        int i39 = (int) vxeVarO1.getLong(i38);
                        int i40 = iE57;
                        long j23 = vxeVarO1.getLong(i40);
                        int i41 = iE58;
                        boolean z6 = ((int) vxeVarO1.getLong(i41)) != 0;
                        int i42 = iE59;
                        long j24 = vxeVarO1.getLong(i42);
                        int i43 = iE60;
                        String strB9 = vxeVarO1.isNull(i43) ? null : vxeVarO1.B0(i43);
                        int i44 = iE61;
                        String strB10 = vxeVarO1.isNull(i44) ? null : vxeVarO1.B0(i44);
                        iE61 = i44;
                        int i45 = iE62;
                        String strB11 = vxeVarO1.isNull(i45) ? null : vxeVarO1.B0(i45);
                        iE62 = i45;
                        int i46 = iE63;
                        Integer numValueOf3 = vxeVarO1.isNull(i46) ? null : Integer.valueOf((int) vxeVarO1.getLong(i46));
                        toaVar.d().getClass();
                        int iA2 = vo3.a(numValueOf3);
                        int i47 = iE64;
                        long j25 = vxeVarO1.getLong(i47);
                        int i48 = iE65;
                        long j26 = vxeVarO1.getLong(i48);
                        int i49 = iE66;
                        int i50 = (int) vxeVarO1.getLong(i49);
                        toaVar.e().getClass();
                        int iE78 = dwa.e(i50);
                        int i51 = iE67;
                        long j27 = vxeVarO1.getLong(i51);
                        int i52 = iE68;
                        int i53 = (int) vxeVarO1.getLong(i52);
                        int i54 = iE69;
                        int i55 = iE43;
                        int i56 = (int) vxeVarO1.getLong(i54);
                        int i57 = iE70;
                        long j28 = vxeVarO1.getLong(i57);
                        int i58 = iE71;
                        int i59 = (int) vxeVarO1.getLong(i58);
                        int i60 = iE72;
                        long j29 = vxeVarO1.getLong(i60);
                        iE71 = i58;
                        int i61 = iE73;
                        byte[] blob4 = vxeVarO1.getBlob(i61);
                        toaVar.e().getClass();
                        List listC2 = dwa.c(blob4);
                        iE73 = i61;
                        iE74 = iE74;
                        kja kjaVarF2 = toaVar.e().f(vxeVarO1.isNull(iE74) ? null : vxeVarO1.getBlob(iE74));
                        int i62 = iE75;
                        Long lValueOf2 = vxeVarO1.isNull(i62) ? null : Long.valueOf(vxeVarO1.getLong(i62));
                        int i63 = iE76;
                        Integer numValueOf4 = vxeVarO1.isNull(i63) ? null : Integer.valueOf((int) vxeVarO1.getLong(i63));
                        if (numValueOf4 != null) {
                            boolValueOf2 = Boolean.valueOf(numValueOf4.intValue() != 0);
                        } else {
                            boolValueOf2 = null;
                        }
                        int i64 = iE77;
                        arrayList2.add(new gga(j16, j17, j18, j19, j20, j21, strB6, xfaVarB2, wjaVarD2, z4, j22, strB7, strB8, c46VarA2, i36, z5, i39, j23, z6, j24, strB9, strB10, strB11, iA2, j25, j26, iE78, j27, i53, i56, j28, i59, j29, listC2, kjaVarF2, lValueOf2, boolValueOf2, vxeVarO1.getLong(i64)));
                        iE76 = i63;
                        iE77 = i64;
                        iE43 = i55;
                        iE69 = i54;
                        iE70 = i57;
                        iE72 = i60;
                        iE41 = iE41;
                        iE42 = i35;
                        iE54 = i34;
                        iE75 = i62;
                        iE55 = i37;
                        iE56 = i38;
                        iE57 = i40;
                        iE58 = i41;
                        iE59 = i42;
                        iE60 = i43;
                        iE63 = i46;
                        iE64 = i47;
                        iE65 = i48;
                        iE66 = i49;
                        iE67 = i51;
                        iE40 = iE40;
                        iE68 = i52;
                        break;
                    }
                    return arrayList2;
                } finally {
                    vxeVarO1.close();
                }
        }
    }
}
