package defpackage;

import android.view.ViewGroup;
import java.util.Arrays;
import java.util.HashMap;

/* JADX INFO: loaded from: classes.dex */
public final class zf4 {
    public int a;
    public final cg4 b;
    public final bg4 c;
    public final ag4 d;
    public final dg4 e;
    public HashMap f;

    public zf4() {
        cg4 cg4Var = new cg4();
        cg4Var.a = 0;
        cg4Var.b = 0;
        cg4Var.c = 1.0f;
        cg4Var.d = Float.NaN;
        this.b = cg4Var;
        bg4 bg4Var = new bg4();
        bg4Var.a = -1;
        bg4Var.b = 0;
        bg4Var.c = -1;
        bg4Var.d = Float.NaN;
        bg4Var.e = Float.NaN;
        bg4Var.f = Float.NaN;
        bg4Var.g = -1;
        bg4Var.h = null;
        bg4Var.i = -1;
        this.c = bg4Var;
        ag4 ag4Var = new ag4();
        ag4Var.a = false;
        ag4Var.d = -1;
        ag4Var.e = -1;
        ag4Var.f = -1.0f;
        ag4Var.g = true;
        ag4Var.h = -1;
        ag4Var.i = -1;
        ag4Var.j = -1;
        ag4Var.k = -1;
        ag4Var.l = -1;
        ag4Var.m = -1;
        ag4Var.n = -1;
        ag4Var.o = -1;
        ag4Var.p = -1;
        ag4Var.q = -1;
        ag4Var.r = -1;
        ag4Var.s = -1;
        ag4Var.t = -1;
        ag4Var.u = -1;
        ag4Var.v = -1;
        ag4Var.w = 0.5f;
        ag4Var.x = 0.5f;
        ag4Var.y = null;
        ag4Var.z = -1;
        ag4Var.A = 0;
        ag4Var.B = 0.0f;
        ag4Var.C = -1;
        ag4Var.D = -1;
        ag4Var.E = -1;
        ag4Var.F = 0;
        ag4Var.G = 0;
        ag4Var.H = 0;
        ag4Var.I = 0;
        ag4Var.J = 0;
        ag4Var.K = 0;
        ag4Var.L = 0;
        ag4Var.M = Integer.MIN_VALUE;
        ag4Var.N = Integer.MIN_VALUE;
        ag4Var.O = Integer.MIN_VALUE;
        ag4Var.P = Integer.MIN_VALUE;
        ag4Var.Q = Integer.MIN_VALUE;
        ag4Var.R = Integer.MIN_VALUE;
        ag4Var.S = Integer.MIN_VALUE;
        ag4Var.T = -1.0f;
        ag4Var.U = -1.0f;
        ag4Var.V = 0;
        ag4Var.W = 0;
        ag4Var.X = 0;
        ag4Var.Y = 0;
        ag4Var.Z = 0;
        ag4Var.a0 = 0;
        ag4Var.b0 = 0;
        ag4Var.c0 = 0;
        ag4Var.d0 = 1.0f;
        ag4Var.e0 = 1.0f;
        ag4Var.f0 = -1;
        ag4Var.g0 = 0;
        ag4Var.h0 = -1;
        ag4Var.l0 = false;
        ag4Var.m0 = false;
        ag4Var.n0 = true;
        ag4Var.o0 = 0;
        this.d = ag4Var;
        dg4 dg4Var = new dg4();
        dg4Var.a = 0.0f;
        dg4Var.b = 0.0f;
        dg4Var.c = 0.0f;
        dg4Var.d = 1.0f;
        dg4Var.e = 1.0f;
        dg4Var.f = Float.NaN;
        dg4Var.g = Float.NaN;
        dg4Var.h = -1;
        dg4Var.i = 0.0f;
        dg4Var.j = 0.0f;
        dg4Var.k = 0.0f;
        dg4Var.l = false;
        dg4Var.m = 0.0f;
        this.e = dg4Var;
        this.f = new HashMap();
    }

    public final void a(uf4 uf4Var) {
        ag4 ag4Var = this.d;
        uf4Var.e = ag4Var.h;
        uf4Var.f = ag4Var.i;
        uf4Var.g = ag4Var.j;
        uf4Var.h = ag4Var.k;
        uf4Var.i = ag4Var.l;
        uf4Var.j = ag4Var.m;
        uf4Var.k = ag4Var.n;
        uf4Var.l = ag4Var.o;
        uf4Var.m = ag4Var.p;
        uf4Var.n = ag4Var.q;
        uf4Var.o = ag4Var.r;
        uf4Var.s = ag4Var.s;
        uf4Var.t = ag4Var.t;
        uf4Var.u = ag4Var.u;
        uf4Var.v = ag4Var.v;
        ((ViewGroup.MarginLayoutParams) uf4Var).leftMargin = ag4Var.F;
        ((ViewGroup.MarginLayoutParams) uf4Var).rightMargin = ag4Var.G;
        ((ViewGroup.MarginLayoutParams) uf4Var).topMargin = ag4Var.H;
        ((ViewGroup.MarginLayoutParams) uf4Var).bottomMargin = ag4Var.I;
        uf4Var.A = ag4Var.R;
        uf4Var.B = ag4Var.Q;
        uf4Var.x = ag4Var.N;
        uf4Var.z = ag4Var.P;
        uf4Var.E = ag4Var.w;
        uf4Var.F = ag4Var.x;
        uf4Var.p = ag4Var.z;
        uf4Var.q = ag4Var.A;
        uf4Var.r = ag4Var.B;
        uf4Var.G = ag4Var.y;
        uf4Var.T = ag4Var.C;
        uf4Var.U = ag4Var.D;
        uf4Var.I = ag4Var.T;
        uf4Var.H = ag4Var.U;
        uf4Var.K = ag4Var.W;
        uf4Var.J = ag4Var.V;
        uf4Var.W = ag4Var.l0;
        uf4Var.X = ag4Var.m0;
        uf4Var.L = ag4Var.X;
        uf4Var.M = ag4Var.Y;
        uf4Var.P = ag4Var.Z;
        uf4Var.Q = ag4Var.a0;
        uf4Var.N = ag4Var.b0;
        uf4Var.O = ag4Var.c0;
        uf4Var.R = ag4Var.d0;
        uf4Var.S = ag4Var.e0;
        uf4Var.V = ag4Var.E;
        uf4Var.c = ag4Var.f;
        uf4Var.a = ag4Var.d;
        uf4Var.b = ag4Var.e;
        ((ViewGroup.MarginLayoutParams) uf4Var).width = ag4Var.b;
        ((ViewGroup.MarginLayoutParams) uf4Var).height = ag4Var.c;
        String str = ag4Var.k0;
        if (str != null) {
            uf4Var.Y = str;
        }
        uf4Var.Z = ag4Var.o0;
        uf4Var.setMarginStart(ag4Var.K);
        uf4Var.setMarginEnd(ag4Var.J);
        uf4Var.a();
    }

    public final Object clone() {
        zf4 zf4Var = new zf4();
        ag4 ag4Var = zf4Var.d;
        ag4Var.getClass();
        ag4 ag4Var2 = this.d;
        ag4Var.a = ag4Var2.a;
        ag4Var.b = ag4Var2.b;
        ag4Var.c = ag4Var2.c;
        ag4Var.d = ag4Var2.d;
        ag4Var.e = ag4Var2.e;
        ag4Var.f = ag4Var2.f;
        ag4Var.g = ag4Var2.g;
        ag4Var.h = ag4Var2.h;
        ag4Var.i = ag4Var2.i;
        ag4Var.j = ag4Var2.j;
        ag4Var.k = ag4Var2.k;
        ag4Var.l = ag4Var2.l;
        ag4Var.m = ag4Var2.m;
        ag4Var.n = ag4Var2.n;
        ag4Var.o = ag4Var2.o;
        ag4Var.p = ag4Var2.p;
        ag4Var.q = ag4Var2.q;
        ag4Var.r = ag4Var2.r;
        ag4Var.s = ag4Var2.s;
        ag4Var.t = ag4Var2.t;
        ag4Var.u = ag4Var2.u;
        ag4Var.v = ag4Var2.v;
        ag4Var.w = ag4Var2.w;
        ag4Var.x = ag4Var2.x;
        ag4Var.y = ag4Var2.y;
        ag4Var.z = ag4Var2.z;
        ag4Var.A = ag4Var2.A;
        ag4Var.B = ag4Var2.B;
        ag4Var.C = ag4Var2.C;
        ag4Var.D = ag4Var2.D;
        ag4Var.E = ag4Var2.E;
        ag4Var.F = ag4Var2.F;
        ag4Var.G = ag4Var2.G;
        ag4Var.H = ag4Var2.H;
        ag4Var.I = ag4Var2.I;
        ag4Var.J = ag4Var2.J;
        ag4Var.K = ag4Var2.K;
        ag4Var.L = ag4Var2.L;
        ag4Var.M = ag4Var2.M;
        ag4Var.N = ag4Var2.N;
        ag4Var.O = ag4Var2.O;
        ag4Var.P = ag4Var2.P;
        ag4Var.Q = ag4Var2.Q;
        ag4Var.R = ag4Var2.R;
        ag4Var.S = ag4Var2.S;
        ag4Var.T = ag4Var2.T;
        ag4Var.U = ag4Var2.U;
        ag4Var.V = ag4Var2.V;
        ag4Var.W = ag4Var2.W;
        ag4Var.X = ag4Var2.X;
        ag4Var.Y = ag4Var2.Y;
        ag4Var.Z = ag4Var2.Z;
        ag4Var.a0 = ag4Var2.a0;
        ag4Var.b0 = ag4Var2.b0;
        ag4Var.c0 = ag4Var2.c0;
        ag4Var.d0 = ag4Var2.d0;
        ag4Var.e0 = ag4Var2.e0;
        ag4Var.f0 = ag4Var2.f0;
        ag4Var.g0 = ag4Var2.g0;
        ag4Var.h0 = ag4Var2.h0;
        ag4Var.k0 = ag4Var2.k0;
        int[] iArr = ag4Var2.i0;
        if (iArr == null || ag4Var2.j0 != null) {
            ag4Var.i0 = null;
        } else {
            ag4Var.i0 = Arrays.copyOf(iArr, iArr.length);
        }
        ag4Var.j0 = ag4Var2.j0;
        ag4Var.l0 = ag4Var2.l0;
        ag4Var.m0 = ag4Var2.m0;
        ag4Var.n0 = ag4Var2.n0;
        ag4Var.o0 = ag4Var2.o0;
        bg4 bg4Var = zf4Var.c;
        bg4Var.getClass();
        bg4 bg4Var2 = this.c;
        bg4Var2.getClass();
        bg4Var.a = bg4Var2.a;
        bg4Var.c = bg4Var2.c;
        bg4Var.e = bg4Var2.e;
        bg4Var.d = bg4Var2.d;
        cg4 cg4Var = this.b;
        int i = cg4Var.a;
        cg4 cg4Var2 = zf4Var.b;
        cg4Var2.a = i;
        cg4Var2.c = cg4Var.c;
        cg4Var2.d = cg4Var.d;
        cg4Var2.b = cg4Var.b;
        dg4 dg4Var = zf4Var.e;
        dg4Var.getClass();
        dg4 dg4Var2 = this.e;
        dg4Var2.getClass();
        dg4Var.a = dg4Var2.a;
        dg4Var.b = dg4Var2.b;
        dg4Var.c = dg4Var2.c;
        dg4Var.d = dg4Var2.d;
        dg4Var.e = dg4Var2.e;
        dg4Var.f = dg4Var2.f;
        dg4Var.g = dg4Var2.g;
        dg4Var.h = dg4Var2.h;
        dg4Var.i = dg4Var2.i;
        dg4Var.j = dg4Var2.j;
        dg4Var.k = dg4Var2.k;
        dg4Var.l = dg4Var2.l;
        dg4Var.m = dg4Var2.m;
        zf4Var.a = this.a;
        return zf4Var;
    }
}
